/* Designer UI: functional routes, continuous motion, both moods and real archived previews. */
const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const base=process.env.ROOMBLOOM_URL||'http://127.0.0.1:8767',go=async route=>{await page.goto(base+'/#'+route);await page.waitForTimeout(500);},act=name=>page.locator('[data-action="'+name+'"]'),hact=name=>page.locator('[data-h-action="'+name+'"]');
 try{
  await page.goto(base);await page.waitForSelector('.welcome-stage');
  // Observe the actual painted path, including the invisible gap between the two flights.
  await page.evaluate(()=>{window.keyFlightFrames=[];const sample=()=>{const key=document.querySelector('.flying-key'),r=key.getBoundingClientRect(),s=getComputedStyle(key),m=new DOMMatrixReadOnly(s.transform);keyFlightFrames.push({x:r.x,y:r.y,right:r.right,bottom:r.bottom,width:r.width,opacity:+s.opacity,angle:Math.atan2(m.b,m.a)*180/Math.PI,w:innerWidth,h:innerHeight});if(!document.querySelector('.intro-complete'))requestAnimationFrame(sample);};requestAnimationFrame(sample);});
  await page.waitForTimeout(1300);
  const one=await page.locator('.flying-key').boundingBox();await page.waitForTimeout(900);const two=await page.locator('.flying-key').boundingBox();assert.ok(two.x>one.x+50);assert.equal(await page.locator('.flying-key').count(),1);
  const center=await page.locator('.our-home').boundingBox();assert.ok(Math.abs(center.x+center.width/2-720)<2,'opening title stays centered');
  await page.waitForSelector('.intro-complete');assert.equal(await page.locator('.login-entry').evaluate(e=>e.inert),false);assert.equal(await page.locator('.flying-key').count(),1);
  const end=await page.locator('.flying-key').boundingBox();assert.ok(Math.abs(end.x+end.width/2-720)<2);assert.ok(end.y>700&&end.y<900);
  const flight=await page.evaluate(()=>keyFlightFrames),visible=frame=>frame.opacity>.01&&frame.right>0&&frame.x<frame.w&&frame.bottom>0&&frame.y<frame.h;
  const exited=flight.findIndex(f=>f.x>=f.w&&f.opacity>.9);assert.ok(exited>=0,'key flies completely out through the right edge');
  const rising=flight.findIndex((f,i)=>i>exited&&visible(f)&&Math.abs(f.angle)<1);assert.ok(rising>exited,'upright key reappears from below');
  assert.ok(flight.slice(exited,rising).some(f=>f.opacity===0),'key disappears between the two flights');
  assert.ok(flight.filter(visible).every(f=>Math.abs(f.angle+90)<1||Math.abs(f.angle)<1),'no visible turn or diagonal connecting flight');
  const ascent=flight.slice(rising).filter(visible);assert.ok(ascent[0].y>ascent.at(-1).y+70);assert.ok(ascent.every(f=>Math.abs(f.x+f.width/2-f.w/2)<2),'second flight rises at the screen center');
  await page.locator('#name').fill('Mia');await page.locator('#login-form button').click();await page.waitForSelector('.welcome-choices');assert.equal(await page.locator('[data-mood-select]').inputValue(),'macaron');
  await page.locator('[data-mood-select]').selectOption('woodland');assert.equal(await page.evaluate(()=>getComputedStyle(document.body).backgroundColor),'rgb(33, 55, 34)');await page.reload();assert.equal(await page.locator('[data-mood-select]').inputValue(),'woodland');await page.locator('[data-mood-select]').selectOption('macaron');console.log('PASS continuous key movement, centered login landing, ID login and two persistent moods');
  await go('/create');await page.locator('#create-form button').click();assert.ok((await page.locator('#form-error').innerText()).length);await page.locator('#roomName').fill('Bloom Cottage');await page.locator('#create-form button').click();await page.waitForSelector('#house-stage canvas');
  const roomId=await page.locator('.house-shell').getAttribute('data-room-id');const saved=await page.evaluate(id=>JSON.parse(localStorage.getItem('roombloom-house-v1:'+id)),roomId);
  await page.locator('.house-mood select').selectOption('woodland');await hact('edit').click();await page.locator('[data-h-setting="layer"]').count().then(async n=>{if(n)await page.locator('[data-h-setting="layer"]').selectOption('OBJECT');});
  // Use the native mode switch if this version renders buttons rather than a select.
  if(!await hact('catalog').count())await page.locator('[data-h-action="setting"][data-value="OBJECT"]').click();
  await hact('catalog').click();assert.ok(await page.locator('.house-object-thumbnail').count()>10);await page.waitForTimeout(300);await page.screenshot({path:require('./test-artifacts.cjs')('rb-mood2-object-menu.png')});await hact('close-dialog').click();await hact('save').click();
  await page.locator('[aria-label="Leave room"]').click();await page.locator('.house-shell').waitFor({state:'detached'});await page.locator('[data-go="/load"]').click();await act('house-preview').click();const src=await page.locator('.house-memory img').getAttribute('src');assert.match(src,/^data:image\/webp;base64,/);assert.ok(src.length>5000);await act('close-modal').click();
  await act('archive-room').click();await page.getByRole('button',{name:'Stay here',exact:true}).click();assert.equal(await page.locator('.room-tile').count(),1);await act('archive-room').click();await act('confirm-archive').click();await page.waitForURL('**/load?tab=archive');await page.waitForSelector('[data-archive="true"]');assert.equal(await page.locator('[data-archive="true"]').count(),1);
  await page.reload();await act('house-preview').click();assert.equal(await page.locator('.house-memory img').getAttribute('src'),src);await page.waitForTimeout(300);await page.screenshot({path:require('./test-artifacts.cjs')('rb-mood2-archive.png')});await act('restore-room').click();await page.waitForSelector('#house-stage canvas');
  const restored=await page.evaluate(id=>JSON.parse(localStorage.getItem('roombloom-house-v1:'+id)),roomId);assert.deepEqual(restored.structure,saved.structure);assert.deepEqual(restored.objects.map(o=>[o.id,o.grid]),saved.objects.map(o=>[o.id,o.grid]));console.log('PASS create validation, themed live editor, real preview capture, archive cancellation/reload and layout-preserving return');
  await page.locator('[aria-label="Leave room"]').click();await page.locator('.house-shell').waitFor({state:'detached'});await go('/join');await page.locator('#invite').fill('NOT-A-HOME');await page.locator('#join-form button').click();assert.match(await page.locator('#form-error').innerText(),/find/);await page.locator('#invite').fill('RB42');await page.locator('#join-form button').click();await act('confirm-join').click();await page.waitForSelector('#house-stage canvas');await page.locator('[aria-label="Leave room"]').click();await page.locator('.house-shell').waitFor({state:'detached'});
  await go('/habits');await page.locator('#sleep').selectOption('Night owl');await page.locator('#pets').selectOption('Pet friendly');await page.locator('#preferences').fill('A quiet kitchen after ten.');await page.locator('#habits-form [type="submit"]').click();await go('/habits');assert.equal(await page.locator('#sleep').inputValue(),'Night owl');assert.equal(await page.locator('#preferences').inputValue(),'A quiet kitchen after ten.');
  await go('/plaza');await page.locator('#search').fill('coffee');await page.locator('#filters-form [type="submit"]').click();await page.waitForFunction(()=>document.querySelectorAll('.person-card').length===1);assert.equal(await page.locator('.person-card').count(),1);await page.locator('.person-card [data-go]').click();await act('request').click();await page.locator('[data-action="respond"][data-value="accepted"]').click();await page.locator('[data-go^="/invite/"]').click();await page.locator('[name="roomId"]').first().check();await page.locator('#invite-form [type="submit"]').click();await act('simulate-join').click();await page.waitForSelector('#house-stage canvas');console.log('PASS join errors/acceptance, habits persistence, profile filtering, connection and invitation');
  await page.locator('[aria-label="Leave room"]').click();await page.locator('.house-shell').waitFor({state:'detached'});await page.locator('[data-mood-select]').selectOption('macaron');await page.setViewportSize({width:390,height:844});
  for(const route of ['/','/homes','/create','/join','/habits','/plaza','/profile','/load']){await go(route);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'no horizontal overflow on '+route);}
  await go('/plaza');await page.screenshot({path:require('./test-artifacts.cjs')('rb-mobile-plaza.png')});await go('/profile');await act('logout').click();await page.waitForSelector('.intro-complete');await page.screenshot({path:require('./test-artifacts.cjs')('rb-mobile-login.png')});await act('replay-intro').click();await act('skip-intro').click();assert.equal(await page.locator('.login-entry').evaluate(e=>e.inert),false);assert.equal(await page.locator('.flying-key').count(),1);console.log('PASS responsive routes, returning login, replay and skip');
  const reduced=await browser.newContext({reducedMotion:'reduce',viewport:{width:390,height:844}}),quiet=await reduced.newPage();await quiet.goto(base);await quiet.waitForSelector('.intro-complete');assert.equal(await quiet.locator('.login-entry').evaluate(e=>e.inert),false);assert.equal(await quiet.locator('[data-action="skip-intro"]').isVisible(),false);await quiet.close();await reduced.close();
  const filePage=await context.newPage();await filePage.goto(require('node:url').pathToFileURL(require('node:path').resolve(__dirname,'../index.html')).href);await filePage.locator('[data-action="skip-intro"]').click();await filePage.locator('#name').fill('Local');await filePage.locator('#login-form button').click();await filePage.waitForSelector('.welcome-choices');assert.equal(await filePage.evaluate(()=>typeof anime.createTimeline),'function');await filePage.close();assert.deepEqual(errors,[]);console.log('PASS reduced-motion login, offline file:// startup and no runtime errors');
 }catch(e){await page.screenshot({path:require('./test-artifacts.cjs')('rb-design-failure.png')});throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
