/* Editing reliability, utility schedules, plant scoring, floating controls and real lamp lighting. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const page=await browser.newPage({viewport:{width:1440,height:1000},timezoneId:'America/Vancouver'}),errors=[];
 page.on('pageerror',e=>{errors.push(e.message);console.error(e.message);});page.on('console',m=>{if(m.type()==='error'&&/THREE|WebGL|shader/.test(m.text()))errors.push(m.text());});
 try{
  await page.addInitScript(()=>{if(!localStorage.getItem('roombloom-demo-v1'))localStorage.setItem('roombloom-demo-v1',JSON.stringify({version:1,loggedIn:true,user:{name:'Test',campus:'Vancouver',habits:{sleep:'Early bird'}},rooms:[{id:'test',name:'Quiet home',code:'TEST',members:[{id:'alex',name:'Alex'},{id:'self',name:'Test'},{id:'sam',name:'Sam'}]}],connections:{},invitations:[]}));});
  await page.route('**/house/editor.js',route=>route.fulfill({contentType:'text/javascript',body:fs.readFileSync(path.join(__dirname,'../house/editor.js'),'utf8')+'\nconst originalMount=RoomBloomHouse.mount;RoomBloomHouse.mount=(...args)=>(window.editor=originalMount(...args));'}));
  const url=(process.env.ROOMBLOOM_URL||'http://127.0.0.1:8767')+'/#/room/test';await page.goto(url);await page.waitForFunction(()=>window.editor?.scene);
  const act=n=>page.locator('[data-h-action="'+n+'"]'),close=()=>act('close-dialog').click(),obj=type=>page.evaluate(type=>editor.house.objects.find(o=>o.objectType===type),type);
  const settle=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
  const open=async type=>{await page.evaluate(type=>editor.interactions.open(editor.house.objects.find(o=>o.objectType===type)),type);};
  const local=n=>{const d=new Date(n);return new Date(n-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
  const point=async(x,y,z)=>{await settle();return page.evaluate(({x,y,z})=>{const s=editor.scene,v=new THREE.Vector3(x,y,z).project(s.camera),r=s.canvas.getBoundingClientRect();return{x:r.x+(v.x+1)*r.width/2,y:r.y+(1-v.y)*r.height/2};},{x,y,z});};
  assert.equal(await page.locator('.house-identity').innerText(),'Quiet home');assert.equal(await page.evaluate(()=>editor.house.lighting.mode),'auto');
  assert.equal(await page.locator('.house-member-stack button:visible').count(),1);assert.equal(await page.locator('.house-member-stack button').first().getAttribute('data-id'),'self');
  await page.locator('.is-self').hover();assert.equal(await page.locator('.house-member-stack button:visible').count(),3);
  await page.locator('[data-h-action="member"][data-id="alex"]').click();await act('member-info').click();assert.match(await page.locator('#house-dialog').innerText(),/Alex.*Info/s);await close();
  await page.locator('.is-self').click();await act('member-info').click();assert.match(await page.locator('#house-dialog').innerText(),/Vancouver/);await close();
  assert.equal(await page.evaluate(()=>editor.tasks.memberId),'self');
  const gear=await page.locator('.house-settings').boundingBox();assert.ok(gear.width<80);assert.equal(await act('edit').evaluate(el=>getComputedStyle(el).backgroundColor),'rgba(0, 0, 0, 0)');
  console.log('PASS compact self-first resident rail, own profile/inboxes, house name and floating gear');
  await page.evaluate(()=>{const H=RoomBloomHouse;editor.mutate(()=>{const h=H.HouseModel.basic(),os=new H.ObjectSystem(h);h.objects=h.objects.filter(o=>o.objectType!=='bowl');for(const [type,x,z]of [['laundry',5,0],['oven',4,3],['floorlamp',2,3]])os.place(type,{grid:{x,y:0,z}},0,1.5);for(const [type,x,z,wallId]of [['art',2,0,'wall-n-2'],['lamp',0,0,'wall-n-0'],['electricity',4,0,'wall-n-4'],['water',0,1,'wall-w-1'],['board',0,2,'wall-w-2']])os.place(type,{grid:{x,y:0,z},wallId},0,1.5);const canvas=document.createElement('canvas');canvas.width=canvas.height=32;const ctx=canvas.getContext('2d');ctx.fillStyle='#4a8d65';ctx.fillRect(0,0,32,32);h.objects.find(o=>o.objectType==='art').customState.image=canvas.toDataURL();editor.house=h;},'Fixture');editor.save();});
  await open('art');assert.equal(await page.locator('.house-art-preview').isVisible(),true);await page.waitForTimeout(3800);assert.equal(await page.locator('.house-art-preview').isVisible(),true);await act('close-art').click();assert.equal(await page.locator('.house-art-preview').count(),0);
  await act('edit').click();await page.locator('[data-h-setting="layer"]').count();await page.evaluate(()=>editor.dispatch('setting',{key:'layer',value:'OBJECT'}));
  await act('catalog').click();await page.locator('[data-h-action="choose-object"][data-id="lamp"]').click();let p=await point(.08,1.5,4.5);await page.mouse.move(p.x,p.y);await page.locator('[data-h-setting="height"]').selectOption('2');await page.locator('[data-h-setting="height"]').focus();await page.keyboard.press('r');assert.equal(await page.evaluate(()=>editor.state.rotation),90);assert.equal(await page.evaluate(()=>!!editor.scene.ghost),true);await page.keyboard.press('Escape');
  p=await point(2.5,1.5,.08);await page.mouse.click(p.x,p.y);assert.equal(await page.evaluate(()=>editor.state.selected?.id), (await obj('art')).id);
  await page.locator('[data-h-setting="objectHeight"]').focus();const before=await obj('art');await page.keyboard.press('r');assert.equal((await obj('art')).rotation,90);await page.keyboard.press('m');assert.equal(await page.evaluate(()=>editor.state.movingId),before.id);
  p=await point(.08,1.5,4.5);await page.mouse.move(p.x,p.y);await page.mouse.click(p.x,p.y);const after=await obj('art');assert.equal(after.id,before.id);assert.equal(after.customState.image,before.customState.image);assert.equal(after.attachedWallId,'wall-w-4');
  await page.keyboard.press('m');await page.keyboard.press('Escape');assert.equal((await obj('art')).attachedWallId,'wall-w-4');const catBefore=await page.evaluate(()=>{editor.state.selected={kind:'animal',id:'pip'};editor.render();return {...editor.house.animal};});await page.keyboard.press('m');p=await point(5.5,.025,4.5);await page.mouse.move(p.x,p.y);await page.mouse.click(p.x,p.y);assert.equal(await page.evaluate(()=>editor.house.animal.lifeId),catBefore.lifeId);assert.equal(await page.evaluate(()=>editor.house.animal.lastFedAt),catBefore.lastFedAt);assert.deepEqual(await page.evaluate(()=>editor.house.animal.grid),{x:5,y:0,z:4});await act('save').click();
  console.log('PASS art explicit close, R with focused height select, selected rotation and M preserving photo/identity');
  await page.evaluate(()=>{window.now=Date.now();Date.now=()=>window.now;});
  for(const type of ['laundry','oven']){
   await open(type);const count=await page.locator('.house-machine').count();
   for(let i=0;i<count;i++){
    const form=page.locator('[data-h-form="laundry-book"]').nth(i);assert.equal(await form.locator('[value="queue"]').isVisible(),false);
    await form.locator('[name="minutes"]').fill('43');const start=await page.evaluate(()=>{const d=new Date(Date.now());return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);});await form.locator('[name="start"]').fill(start);await form.locator('[value="reserve"]').click();
    assert.equal(await form.locator('[value="reserve"]').isDisabled(),true);assert.equal(await form.locator('[value="queue"]').isVisible(),true);await form.locator('[name="memberId"]').selectOption('alex');await form.locator('[value="queue"]').click();
   }await close();
  }
  console.log('PASS active/idle Reserve and Join Queue rules on all three appliances');
  await open('water');await page.locator('[name="note"]').fill('Water payment');await page.locator('[data-h-form="bill-save"] button').click();assert.ok((await obj('water')).customState.bill);await close();
  await open('electricity');await page.locator('[name="memberId"]').selectOption('alex');await page.locator('[name="note"]').fill('Electricity payment');await page.locator('[data-h-form="bill-save"] button').click();await close();
  assert.ok(await page.evaluate(()=>editor.tasks.items.some(t=>t.source==='Water bill')));assert.equal(await page.evaluate(()=>editor.tasks.items.some(t=>t.source==='Electricity bill')),false);
  await act('arrangement').click();assert.match(await page.locator('.house-agenda').innerText(),/Water bill/);assert.match(await page.locator('.house-agenda').innerText(),/Electricity bill/);assert.match(await page.locator('.house-agenda').innerText(),/Oven/);assert.doesNotMatch(await page.locator('.house-agenda').innerText(),/Feed Pip/);await page.locator('[name="scope"]').selectOption('mine');await page.locator('[data-h-form="arrangement-filter"] [type="submit"]').click();assert.doesNotMatch(await page.locator('.house-agenda').innerText(),/Electricity bill/);await close();
  await page.evaluate(()=>{const H=RoomBloomHouse,now=Date.now();editor.mutate(()=>{const p=editor.house.objects.find(o=>o.objectType==='plant');p.customState.growth.placedAt=now-8*3600000;const b=editor.house.objects.find(o=>o.objectType==='board');H.HouseFeatures.addTask(b,'Late shared chore',['self','alex'],now-4*3600000,editor.options.members,now-5*3600000);},'Overdue fixture');editor.updateRoomTime();editor.save();});
  assert.equal((await obj('plant')).customState.growth.score,98);await open('plant');assert.match(await page.locator('#house-dialog').innerText(),/98 \/ 100/);await page.locator('#house-dialog summary').click();assert.match(await page.locator('.house-growth-history').innerText(),/Placed/);await close();
  assert.match(await page.locator('.house-task-card').first().innerText(),/Overdue 4h/);await page.locator('.house-task-card').first().click();await act('personal-complete').click();assert.equal((await obj('plant')).customState.growth.score,99);await page.evaluate(()=>editor.updateRoomTime());assert.equal((await obj('plant')).customState.growth.score,99);
  console.log('PASS utility assignment, integrated arrangement, offline plant scoring/history and overdue elapsed');
  await open('window');await page.locator('[data-h-light-range]').focus();await page.keyboard.press('Home');await close();await settle();assert.ok(await page.evaluate(()=>[...editor.scene.entries.values()].filter(e=>e.lamp?.visible).length===2));
  assert.ok(await page.evaluate(()=>[...editor.scene.entries.values()].filter(e=>e.lamp).every(e=>e.lamp.castShadow&&e.lamp.shadow.map)));
  await page.screenshot({path:require('./test-artifacts.cjs')('roombloom-lamps-night.png')});await open('floorlamp');await page.locator('[name="on"]').uncheck();await page.locator('[data-h-form="lamp-save"] button').click();await close();assert.equal((await obj('floorlamp')).customState.light.on,false);
  await act('edit').click();assert.equal(await page.evaluate(()=>editor.scene.grid.visible),true);await page.screenshot({path:require('./test-artifacts.cjs')('roombloom-lamps-grid.png')});await act('save').click();
  await act('pet-status').click();await page.locator('[data-pip-mute]').check();await page.evaluate(()=>{window.meows=0;editor.tasks.bell.meow=()=>window.meows++;editor.tasks.nextMeow=0;editor.tasks.tick();});assert.equal(await page.evaluate(()=>window.meows),0);
  await page.locator('[data-pip-mute]').uncheck();await page.evaluate(()=>{editor.tasks.nextMeow=0;editor.tasks.tick();});assert.equal(await page.evaluate(()=>window.meows),1);await page.locator('[data-pip-mute]').check();await act('close-pet').click();
  await page.reload();await page.waitForFunction(()=>window.editor?.scene);assert.equal(await page.evaluate(()=>editor.tasks.muted),true);assert.equal((await obj('art')).customState.image,before.customState.image);assert.equal((await obj('plant')).customState.growth.score,99);
  await page.setViewportSize({width:390,height:844});await act('frame').click();await settle();await page.screenshot({path:require('./test-artifacts.cjs')('roombloom-updates-mobile.png')});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await act('arrangement').click();assert.equal(await page.evaluate(()=>document.querySelector('#house-dialog').getBoundingClientRect().right<=innerWidth),true);
  assert.deepEqual(errors,[]);console.log('PASS lamp lighting/shadows, night edit grid, meow mute persistence, saved photos/points and mobile layout');
 }catch(error){await page.screenshot({path:require('./test-artifacts.cjs')('roombloom-updates-failure.png')});console.error(await page.locator('#house-dialog').innerText());throw error;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
