/* Refrigerator/restocking, cleaning tasks, long tables, model import and persistent Pip absence. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
function glb(external=false){
 const positions=new Float32Array([0,0,0,2,0,0,0,6,0, 0,0,0,0,0,2,2,0,0, 0,0,0,0,6,0,0,0,2, 2,0,0,0,0,2,0,6,0]);
 const json={asset:{version:'2.0'},scene:0,scenes:[{nodes:[0]}],nodes:[{mesh:0}],meshes:[{primitives:[{attributes:{POSITION:0},material:0}]}],materials:[{pbrMetallicRoughness:{baseColorFactor:[.5,.8,.7,1],metallicFactor:0,roughnessFactor:.8},doubleSided:true}],buffers:[{byteLength:positions.byteLength,...(external?{uri:'https://invalid.example/model.bin'}:{})}],bufferViews:[{buffer:0,byteOffset:0,byteLength:positions.byteLength}],accessors:[{bufferView:0,componentType:5126,count:12,type:'VEC3',min:[0,0,0],max:[2,6,2]}]};
 let data=Buffer.from(JSON.stringify(json));data=Buffer.concat([data,Buffer.alloc((4-data.length%4)%4,32)]);const binary=Buffer.from(positions.buffer),header=Buffer.alloc(20),binHead=Buffer.alloc(8);header.writeUInt32LE(0x46546c67);header.writeUInt32LE(2,4);header.writeUInt32LE(28+data.length+binary.length,8);header.writeUInt32LE(data.length,12);header.writeUInt32LE(0x4e4f534a,16);binHead.writeUInt32LE(binary.length);binHead.writeUInt32LE(0x004e4942,4);return Buffer.concat([header,data,binHead,binary]);
}
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const context=await browser.newContext({viewport:{width:1280,height:900}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 try{
  await context.addInitScript(()=>{localStorage.setItem('roombloom-demo-v1',JSON.stringify({version:1,loggedIn:true,user:{name:'Test'},rooms:[{id:'additions',name:'Home',code:'NEW',members:[{id:'self'},{id:'alex',name:'Alex'}]}],connections:{},invitations:[]}));});
  await page.route('**/house/editor.js',r=>r.fulfill({contentType:'text/javascript',body:fs.readFileSync(path.join(__dirname,'../house/editor.js'),'utf8')+'\nconst originalMount=RoomBloomHouse.mount;RoomBloomHouse.mount=(...args)=>(window.editor=originalMount(...args));'}));
  await page.goto((process.env.ROOMBLOOM_URL||'http://127.0.0.1:8767')+'/#/room/additions');await page.waitForFunction(()=>window.editor?.scene);
  const act=n=>page.locator('[data-h-action="'+n+'"]'),open=type=>page.evaluate(type=>editor.interactions.open(editor.house.objects.find(o=>o.objectType===type)),type),close=()=>act('close-dialog').click();
  await page.evaluate(()=>{const H=RoomBloomHouse;editor.mutate(()=>{editor.house=H.HouseModel.basic();editor.house.objects=[];const sys=new H.ObjectSystem(editor.house),t=(x,z)=>({grid:{x,y:0,z}});sys.place('fridge',t(0,1),0,1.5);sys.place('vacuum',t(0,2),0,1.5);sys.place('plant',t(0,3),0,1.5);sys.place('longtable',t(1,1),0,1.5);sys.place('board',{...t(2,0),wallId:'wall-n-2'},0,1.5);},'Test room');editor.save();});
  await open('fridge');const add=page.locator('[data-h-form="fridge-add"]');await add.locator('[name="name"]').fill('Milk');await add.locator('[name="quantity"]').fill('0');await add.locator('[type="submit"]').click();assert.equal(await page.evaluate(()=>editor.house.objects.find(o=>o.objectType==='fridge').customState.inventory?.length||0),0);
  await add.locator('[name="quantity"]').fill('2');await add.locator('[type="submit"]').click();await add.locator('[name="name"]').fill('Peas');await add.locator('[name="section"]').selectOption('frozen');await add.locator('[type="submit"]').click();
  const milk=page.locator('.house-inventory-row').filter({hasText:'Milk'});await milk.locator('[data-h-action="fridge-plus"]').click();assert.equal(await milk.locator('output').innerText(),'3');await milk.locator('[data-h-action="fridge-minus"]').click();await milk.locator('[data-h-action="fridge-minus"]').click();await milk.locator('[data-h-action="fridge-minus"]').click();
  assert.equal(await page.locator('[data-h-form="fridge-restock"] [name="memberId"]').inputValue(),'self');assert.equal(await page.locator('[name="title"]').inputValue(),'補貨 Milk');await page.locator('[data-h-form="fridge-restock"] [type="submit"]').click();assert.equal(await page.evaluate(()=>editor.tasks.items.some(t=>t.title==='補貨 Milk')),true);assert.equal(await page.evaluate(()=>RoomBloomHouse.HouseTasks.forMember(editor.house,'alex').some(t=>t.title==='補貨 Milk')),false);
  assert.equal(await milk.locator('output').innerText(),'0');assert.equal(await milk.locator('[data-h-action="fridge-minus"]').isDisabled(),true);await milk.locator('[data-h-action="fridge-plus"]').click();assert.equal(await milk.locator('output').innerText(),'1');
  await page.locator('.house-inventory-row').filter({hasText:'Peas'}).locator('[data-h-action="fridge-minus"]').click();await close();assert.equal(await page.locator('[data-h-form="fridge-add"]').isVisible(),true);assert.equal(await page.evaluate(()=>editor.tasks.items.filter(t=>t.title.startsWith('補貨')).length),1);await close();
  const task=page.locator('.house-task-card').filter({hasText:'補貨 Milk'});await task.click();await act('personal-complete').click();assert.equal(await page.evaluate(()=>editor.house.objects.find(o=>o.objectType==='plant').customState.growth.history.length),1);
  await open('fridge');await add.locator('[name="name"]').fill('Ice');await add.locator('[name="section"]').selectOption('frozen');await add.locator('[name="quantity"]').fill('3');await add.locator('[type="submit"]').click();await close();await page.reload();await page.waitForFunction(()=>window.editor?.scene);await open('fridge');assert.equal(await page.locator('.house-fridge-section').filter({hasText:'Frozen'}).locator('.house-inventory-row').filter({hasText:'Ice'}).locator('output').innerText(),'3');await close();console.log('PASS refrigerator quantities, per-section persistence, restock confirmation/cancel, assigned board task and chore credit');
  await open('vacuum');assert.match(await page.locator('#house-dialog').innerText(),/Cleaning rotation/);await page.locator('[name="turn0"]').selectOption('self');await page.locator('[name="turn1"]').selectOption('alex');await page.locator('[name="interval"]').fill('2');await page.locator('[name="unit"]').selectOption('hours');await page.locator('[data-h-form="trash-save"] [type="submit"]').click();assert.equal(await page.evaluate(()=>editor.tasks.items.some(t=>t.title==='Clean the house')),true);await act('trash-done').click();assert.equal(await page.evaluate(()=>editor.tasks.items.some(t=>t.title==='Clean the house')),false);await close();await act('arrangement').click();assert.match(await page.locator('.house-agenda').innerText(),/Clean the house/);await close();console.log('PASS cleaning rotation, personal identity, completion and arrangement');
  await act('edit').click();await page.evaluate(()=>editor.dispatch('setting',{key:'layer',value:'OBJECT'}));await act('catalog').click();assert.equal(await page.locator('.house-object-thumbnail[src^="data:image/png"]').count(),20);await page.screenshot({path:require('./test-artifacts.cjs')('roombloom-object-thumbnails.png')});await close();
  await page.evaluate(()=>{const table=editor.house.objects.find(o=>o.objectType==='longtable');editor.mutate(()=>{for(const slot of [0,4,7])editor.objects.place('speaker',{grid:table.grid,supportId:table.id,supportSlot:slot},0,1.5);},'Table items');});
  for(const rotation of [0,90,180,270]){
   const positions=await page.evaluate(rotation=>{const h=editor.house,s=editor.scene,t=h.objects.find(o=>o.objectType==='longtable');editor.mutate(()=>{t.rotation=rotation;},'Rotate long table');s.scene.updateMatrixWorld(true);const root=s.entries.get(t.id).root;return h.objects.filter(o=>o.supportId===t.id).map(o=>{const e=s.entries.get(o.id),local=root.worldToLocal(e.root.position.clone());return{x:local.x,z:local.z,slot:o.supportSlot,center:s.entries.get(t.id).root.position.toArray()};});},rotation);
   for(const p of positions){assert.ok(Math.abs(p.x-(Math.floor(p.slot/4)-.5+(p.slot%2?.19:-.19)))<1e-6);assert.ok(Math.abs(p.z-(p.slot%4>=2?.19:-.19))<1e-6);}
  }console.log('PASS real thumbnails and long-table child transforms in four rotations');
  await act('catalog').click();await page.locator('[data-h-action="choose-object"][data-id="custom"]').click();const modelForm=page.locator('[data-h-form="model-import"]');await modelForm.locator('[name="file"]').setInputFiles({name:'test.glb',mimeType:'model/gltf-binary',buffer:glb()});await modelForm.locator('[name="width"]').fill('2');await modelForm.locator('[name="height"]').fill('3.1');await modelForm.locator('[type="submit"]').click();assert.equal(await page.evaluate(()=>editor.state.tool),'SELECT');await modelForm.locator('[name="height"]').fill('3');await modelForm.locator('[type="submit"]').click();await page.waitForFunction(()=>editor.state.furniture==='custom'&&editor.state.customObject);
  await page.keyboard.press('r');assert.equal(await page.evaluate(()=>editor.state.rotation),90);await page.evaluate(()=>editor.activate({grid:{x:4,y:0,z:2}}));
  const modelId=await page.evaluate(()=>editor.house.objects.find(o=>o.objectType==='custom').id);assert.equal(await page.evaluate(id=>editor.scene.entries.get(id).root.children.length,modelId),1);
  await page.evaluate(id=>{editor.state.selected={kind:'object',id};editor.render();},modelId);await page.keyboard.press('r');assert.equal(await page.evaluate(id=>editor.house.objects.find(o=>o.id===id).rotation,modelId),180);await page.keyboard.press('m');await page.evaluate(()=>editor.activate({grid:{x:3,y:0,z:3}}));
  const bounds=await page.evaluate(id=>{const o=editor.house.objects.find(o=>o.id===id),root=editor.scene.entries.get(id).root;return{size:o.size,meshSize:new THREE.Box3().setFromObject(root).getSize(new THREE.Vector3()).toArray(),grid:o.grid};},modelId);assert.deepEqual(bounds.size,{x:2,y:3,z:1});assert.ok(bounds.meshSize[1]<=3.00001);assert.equal(bounds.grid.z,3);
  await act('save').click();await page.reload();await page.waitForFunction(id=>editor?.scene?.entries.get(id)?.root.children[0]?.geometry.attributes.position.count===12,modelId);assert.equal(await page.evaluate(()=>editor.house.objects.find(o=>o.objectType==='custom').customState.model.name),'test.glb');
  const roundtrip=await page.evaluate(async()=>{const H=RoomBloomHouse,packed=await H.MediaStore.pack(editor.house),o=packed.objects.find(o=>o.objectType==='custom'),asset=packed.assets[o.customState.model.id];const restored=await H.MediaStore.hydrate(H.ImportExportSystem.parse(H.ImportExportSystem.serialize(packed))),next=restored.objects.find(o=>o.objectType==='custom');return{mime:asset.mime,bytes:(await H.MediaStore.get(next.customState.model.id)).size,same:JSON.stringify(next.size)===JSON.stringify(o.size),newId:next.customState.model.id!==o.customState.model.id};});assert.equal(roundtrip.mime,'model/gltf-binary');assert.equal(roundtrip.bytes,glb().length);assert.equal(roundtrip.same,true);assert.equal(roundtrip.newId,true);
  const invalid=await page.evaluate(async base64=>{try{await RoomBloomHouse.CustomModels.parse(Uint8Array.from(atob(base64),c=>c.charCodeAt(0)).buffer);return '';}catch(e){return e.message;}},glb(true).toString('base64'));assert.match(invalid,/external/);console.log('PASS GLB import, 3-cell limit, R/M, model rendering, IndexedDB reload, portable JSON and rejected external files');
  await page.evaluate(()=>{editor.mutate(()=>editor.objects.remove('pip'),'Remove Pip');editor.house.animal.absentSince=Date.now()-599000;editor.save();editor.tasks.tick();});assert.equal(await page.evaluate(()=>editor.tasks.items.some(t=>t.kind==='cat-missing')),false);
  await page.evaluate(()=>{editor.house.animal.absentSince=Date.now()-601000;editor.save();editor.tasks.tick();});await page.reload();await page.waitForFunction(()=>window.editor?.tasks.items.some(t=>t.kind==='cat-missing'));const missing=page.locator('.house-task-card').filter({hasText:'Bring Pip home'});await missing.click();await act('personal-complete').click();assert.equal(await page.evaluate(()=>editor.state.furniture),'cat');await page.evaluate(()=>editor.activate({grid:{x:2,y:0,z:2}}));assert.equal(await page.evaluate(()=>editor.tasks.items.some(t=>t.kind==='cat-missing')),false);await act('save').click();console.log('PASS cat absence threshold, reload persistence, Add Pip action and automatic resolution');
  const history=await page.evaluate(async()=>{await editor.dispatch('edit');editor.mutate(()=>editor.objects.remove('pip'),'Remove cat');editor.house.animal.absentSince=Date.now()-900000;await editor.dispatch('undo');const returned=editor.house.animal.placed,now=Date.now();await editor.dispatch('redo');const restarted=editor.house.animal.absentSince>=now,missing=editor.tasks.items.some(t=>t.kind==='cat-missing');await editor.dispatch('undo');await editor.dispatch('save');return{returned,restarted,missing};});assert.deepEqual(history,{returned:true,restarted:true,missing:false});console.log('PASS undo/redo respects continuous cat absence');
  await page.setViewportSize({width:390,height:844});await open('fridge');await page.screenshot({path:require('./test-artifacts.cjs')('roombloom-fridge-mobile.png')});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await close();assert.deepEqual(errors,[]);
 }catch(e){await page.screenshot({path:require('./test-artifacts.cjs')('roombloom-additions-failure.png')});console.error(await page.locator('#house-dialog').innerText());throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
