/* Run against the local HTTP preview. Requires Playwright and Chrome; uses an isolated profile. */
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
 page.on('pageerror',error=>{errors.push(error.message);console.error('Browser error:',error.message);});
 try{
  await page.addInitScript(()=>localStorage.setItem('roombloom-demo-v1',JSON.stringify({version:1,loggedIn:true,user:{name:'Test',campus:'',habits:null},rooms:[{id:'test',name:'Test house',code:'TEST',members:[{id:'self',name:'Test'}]}],connections:{},invitations:[]})));
  await page.route('**/house/editor.js',route=>route.fulfill({contentType:'text/javascript',body:fs.readFileSync(path.join(__dirname,'../house/editor.js'),'utf8')+'\nconst originalMount=RoomBloomHouse.mount;RoomBloomHouse.mount=(...args)=>(window.editor=originalMount(...args));'}));
  await page.goto((process.env.ROOMBLOOM_URL||'http://127.0.0.1:8767')+'/#/room/test');
  await page.waitForFunction(()=>window.editor);assert.ok(await page.evaluate(()=>!!editor.scene),await page.locator('#house-stage').innerText());
  const action=name=>page.locator('[data-h-action="'+name+'"]');
  const settle=()=>page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
  const snapshot=()=>page.evaluate(()=>({house:editor.house,state:editor.state,undo:editor.undoStack.length,redo:editor.redoStack.length,target:editor.scene.controls.target.toArray(),zoom:editor.scene.camera.zoom}));
  const point=async(x,z,y=.025)=>{await settle();return page.evaluate(({x,y,z})=>{const scene=editor.scene,p=new THREE.Vector3(x,y,z).project(scene.camera),r=scene.canvas.getBoundingClientRect();return{x:r.x+(p.x+1)*r.width/2,y:r.y+(1-p.y)*r.height/2};},{x,y,z});};
  const click=async(x,z,button='left',y=.025)=>{const p=await point(x,z,y);await page.mouse.click(p.x,p.y,{button});};
  const drag=async(a,b,button='left')=>{await page.mouse.move(a.x,a.y);await page.mouse.down({button});await page.mouse.move(b.x,b.y,{steps:1});await page.mouse.up({button});};
  const reset=async(type='empty')=>{await action('new-house').click();await page.locator('[data-h-action="reset-house"][data-value="'+type+'"]').click();await settle();};
  const choose=async(type)=>{await action('catalog').click();await page.locator('[data-h-action="choose-object"][data-id="'+type+'"]').click();};
  const layer=value=>page.locator('[data-h-action="setting"][data-key="layer"][data-value="'+value+'"]').click();
  const build=async value=>{await action('type-menu').hover();await page.locator('[data-key="build"][data-value="'+value+'"]').click();await settle();};
  await action('edit').click();await settle();
  assert.equal(await action('type-menu').innerText(),'Type');assert.equal((await snapshot()).state.build,null);
  await action('type-menu').click();assert.equal((await snapshot()).state.tool,'SELECT');
  await page.locator('#house-stage canvas').focus();
  assert.equal(await page.locator('#house-stage canvas').evaluate(el=>getComputedStyle(el).outlineStyle),'none');
  await page.keyboard.press('Tab');
  assert.equal(await page.evaluate(()=>document.activeElement.matches('button')),true);
  assert.notEqual(await page.evaluate(()=>getComputedStyle(document.activeElement).outlineStyle),'none');
  await page.mouse.click(80,150);
  assert.equal(await page.locator('#house-stage canvas').evaluate(el=>getComputedStyle(el).outlineStyle),'none');
  console.log('PASS canvas has no browser outline; keyboard controls retain focus indicators');
  for(const removed of ['storage','done','rotate','pan','zoom-in','zoom-out','grid-toggle','undo','redo','delete-mode','interact','clear-selection'])assert.equal(await action(removed).count(),0,removed);
  assert.equal(await action('help').count(),1);assert.equal(await action('frame').getAttribute('aria-label'),'Reset angle');
  assert.equal(await page.locator('[data-h-setting="selected"], [data-h-setting="side"]').count(),0);
  assert.equal(await action('select-mode').count(),0);assert.equal(await action('texture').innerText(),'Texture');
  const savePosition=await action('save').boundingBox();
  assert.equal(await action('export').isVisible(),false);await action('save').hover();
  assert.equal(await action('export').isVisible(),true);assert.equal(await action('import').isVisible(),true);
  assert.deepEqual(await action('save').boundingBox(),savePosition);
  const exportPosition=await action('export').boundingBox(),importPosition=await action('import').boundingBox();
  assert.ok(exportPosition.x<savePosition.x&&savePosition.x<importPosition.x);
  const moveFromSave=async(name)=>{
    await action('save').hover();
    const target=await action(name).boundingBox(),y=savePosition.y+savePosition.height/2;
    const gapX=name==='export'?(target.x+target.width+savePosition.x)/2:(savePosition.x+savePosition.width+target.x)/2;
    await page.mouse.move(gapX,y,{steps:12});
    assert.equal(await action('export').isVisible(),true,'Export stays visible in the '+name+' gap');
    assert.equal(await action('import').isVisible(),true,'Import stays visible in the '+name+' gap');
    await page.mouse.move(target.x+target.width/2,y,{steps:12});
    assert.equal(await action(name).isVisible(),true);
    assert.deepEqual(await action('save').boundingBox(),savePosition);
  };
  await moveFromSave('export');await moveFromSave('import');
  await page.mouse.move(importPosition.x+importPosition.width+20,savePosition.y+savePosition.height/2,{steps:12});
  assert.equal(await action('export').isVisible(),false);assert.equal(await action('import').isVisible(),false);
  await moveFromSave('export');
  await page.screenshot({path:require('./test-artifacts.cjs')('roombloom-save-menu.png')});
  await action('export').click();assert.equal(await page.locator('.house-json-preview').count(),1);await action('close-dialog').click();
  await moveFromSave('import');await action('import').click();assert.equal(await page.locator('#house-import-file').count(),1);await action('close-dialog').click();
  await action('type-menu').hover();const typePosition=await action('type-menu').boundingBox(),floorPosition=await page.locator('[data-key="build"][data-value="floor"]').boundingBox();
  assert.ok(floorPosition.y<typePosition.y);await page.mouse.move(80,150);
  console.log('PASS dock hierarchy, stationary SAVE, horizontal Export/Import and vertical Type');
  await reset();await build('floor');const start=await snapshot();
  await drag(await point(.5,.5),await point(3.5,.5));
  let s=await snapshot();assert.equal(s.house.structure.floors.length,4);assert.equal(s.undo,start.undo+1);
  assert.equal(s.state.build,null);assert.equal(s.state.tool,'SELECT');assert.equal(await action('type-menu').innerText(),'Type');
  await click(4.5,.5);assert.equal((await snapshot()).house.structure.floors.length,4);
  await page.keyboard.press('Control+z');assert.equal((await snapshot()).house.structure.floors.length,0);
  await page.keyboard.press('Control+Shift+z');assert.equal((await snapshot()).house.structure.floors.length,4);
  await drag(await point(3.5,.5),await point(.5,.5),'right');assert.equal((await snapshot()).house.structure.floors.length,0);
  await page.keyboard.press('Meta+z');assert.equal((await snapshot()).house.structure.floors.length,4);
  console.log('PASS continuous build/remove, one-stroke undo and Ctrl/Cmd redo');
  await build('wall');
  await drag(await point(.5,.5),await point(3.5,.5));assert.equal((await snapshot()).house.structure.walls.length,4);
  await build('door');
  await drag(await point(.5,0,1.2),await point(3.5,0,1.2));assert.equal((await snapshot()).house.structure.doors.length,4);
  await page.keyboard.press('Control+z');assert.equal((await snapshot()).house.structure.doors.length,0);
  await drag(await point(3.5,0,1.2),await point(.5,0,1.2),'right');assert.equal((await snapshot()).house.structure.walls.length,0);
  await action('texture').click();await drag(await point(.5,.5),await point(3.5,.5));assert.equal(Object.keys((await snapshot()).house.materials).length,4);
  await drag(await point(.5,.5),await point(3.5,.5),'right');assert.equal(Object.keys((await snapshot()).house.materials).length,0);
  console.log('PASS continuous walls, doors, material paint and restore');
  await page.locator('#house-stage canvas').focus();await page.keyboard.press('Escape');await settle();
  const outside={x:80,y:150},outsideEnd={x:180,y:210};s=await snapshot();
  await drag(outside,outsideEnd);assert.notDeepEqual((await snapshot()).target,s.target);assert.equal((await snapshot()).house.structure.floors.length,4);
  s=await snapshot();await drag(outsideEnd,outside,'right');assert.notDeepEqual((await snapshot()).target,s.target);
  await action('frame').click();assert.equal((await snapshot()).zoom,1);
  console.log('PASS left/right blank-space pan and reset angle');
  await layer('OBJECT');assert.equal(await action('catalog').innerText(),'＋');
  await choose('plant');assert.equal(await action('catalog').innerText(),'＋');await click(.5,.5);s=await snapshot();assert.equal(s.house.objects.length,1);assert.equal(s.state.tool,'SELECT');assert.equal(s.state.furniture,null);assert.equal(await action('catalog').innerText(),'＋');
  assert.equal(await page.locator('#house-stage canvas').evaluate(el=>getComputedStyle(el).outlineStyle),'none');
  await click(1.5,.5);assert.equal((await snapshot()).house.objects.length,1);
  await choose('sofa');await click(.5,.5,'right',.3);s=await snapshot();assert.equal(s.house.objects.length,1);assert.equal(s.state.furniture,null);
  await choose('bed');await page.keyboard.press('Escape');assert.equal((await snapshot()).state.tool,'SELECT');
  await click(.5,.5,'left',.3);assert.equal((await snapshot()).state.selected.kind,'object');assert.equal(await page.locator('#house-dialog').evaluate(el=>el.open),false);
  await page.mouse.move(80,150);assert.equal(await page.evaluate(()=>editor.scene.selection.current),(await snapshot()).house.objects[0].id);
  await page.screenshot({path:require('./test-artifacts.cjs')('roombloom-selected.png')});
  await page.mouse.click(80,150);assert.equal((await snapshot()).state.selected,null);
  await click(.5,.5,'right',.3);assert.equal((await snapshot()).house.objects.length,0);
  await page.keyboard.press('Control+z');assert.equal((await snapshot()).house.objects.length,1);
  console.log('PASS single furniture placement, right-click/Esc cancel, selection, deletion and undo');
  await choose('cat');await click(1.5,.5);assert.equal((await snapshot()).house.animal.placed,true);
  await action('catalog').click();assert.equal(await page.locator('[data-id="cat"]').isDisabled(),true);await action('close-dialog').click();
  await click(1.5,.5,'right',.3);assert.equal((await snapshot()).house.animal.placed,false);
  await choose('cat');await click(2.5,.5);assert.equal((await snapshot()).house.animal.placed,true);
  await layer('STRUCTURE');await click(2.5,.5,'right');
  // Removing an interior floor is rejected and must preserve the cat.
  assert.equal((await snapshot()).house.animal.placed,true);
  await click(3.5,.5,'right');await click(2.5,.5,'right');assert.equal((await snapshot()).house.animal.placed,false);
  await page.keyboard.press('Control+z');assert.equal((await snapshot()).house.animal.placed,true);
  console.log('PASS cat limit, removal, re-placement and support loss');
  await reset('basic');await layer('OBJECT');await choose('sofa');
  await page.mouse.move((await point(4.5,1.5,.35)).x,(await point(4.5,1.5,.35)).y);
  const rotations=(await snapshot()).house.objects.map(o=>o.rotation);await page.keyboard.press('r');
  s=await snapshot();assert.equal(s.state.rotation,90);assert.deepEqual(s.house.objects.map(o=>o.rotation),rotations);
  await page.keyboard.press('Escape');
  await click(5.5,3.5,'left',.4);await settle();
  await page.screenshot({path:require('./test-artifacts.cjs')('roombloom-desktop.png')});
  await action('save').click();assert.equal((await snapshot()).state.editing,false);
  const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('roombloom-house-v1:test')));assert.equal(saved.storage,undefined);assert.equal(saved.animal.placed,true);
  await action('edit').click();await page.setViewportSize({width:390,height:844});await settle();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await action('frame').click();await page.screenshot({path:require('./test-artifacts.cjs')('roombloom-mobile.png')});
  console.log('PASS preview-only rotation, Save finishes editing, persistence, mobile layout');
  await layer('STRUCTURE');
  await build('floor');await settle();
  const cdp=await page.context().newCDPSession(page),touch=(id,x,y)=>({id,x,y,radiusX:1,radiusY:1,force:1});
  const floors=(await snapshot()).house.structure.floors.length,zoom=(await snapshot()).zoom;
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[touch(1,140,200)]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[touch(1,140,200),touch(2,240,200)]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[touch(1,110,200),touch(2,270,200)]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  assert.equal((await snapshot()).house.structure.floors.length,floors);assert.ok((await snapshot()).zoom>zoom);
  await page.locator('#house-stage canvas').focus();await page.keyboard.press('Escape');await settle();const camera=(await snapshot()).target;
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[touch(1,40,110)]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[touch(1,90,150)]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  assert.notDeepEqual((await snapshot()).target,camera);
  console.log('PASS touch pinch without edits and single-finger blank-space pan');
  await page.setViewportSize({width:1440,height:1000});await reset('basic');await layer('STRUCTURE');await build('wall');
  const rotationPoint=await point(.5,.5);await page.mouse.move(rotationPoint.x,rotationPoint.y);await page.keyboard.press('r');
  assert.equal((await snapshot()).state.side,'W');
  assert.ok(Math.abs(await page.evaluate(()=>editor.scene.ghost.rotation.y)-Math.PI/2)<.001);
  await build('door');const doorPoint=await point(0,.5,1.2);await page.mouse.move(doorPoint.x,doorPoint.y);
  assert.equal(await page.evaluate(()=>editor.lastHover.wallId),'wall-w-0');
  await page.keyboard.press('r');assert.equal(await page.evaluate(()=>editor.lastHover.wallId),'wall-n-0');
  await build('floor');await page.keyboard.press('r');assert.equal((await snapshot()).state.buildRotation,270);
  await action('texture').click();await page.locator('[data-key="finish"][data-value="tile"]').click();
  await page.locator('[data-h-setting="color"]').fill('#123abc');
  assert.equal((await snapshot()).state.color,'#123abc');assert.equal((await snapshot()).state.finish,'tile');
  await page.screenshot({path:require('./test-artifacts.cjs')('roombloom-texture-menu.png')});
  await build('door');await layer('OBJECT');assert.equal(await page.locator('[aria-label="Object tools"] button').count(),1);assert.equal(await action('catalog').innerText(),'＋');
  await action('save').click();await action('edit').click();assert.equal((await snapshot()).state.layer,'OBJECT');
  await layer('STRUCTURE');assert.equal(await action('type-menu').innerText(),'Type');
  await page.reload();await page.waitForFunction(()=>window.editor);assert.ok(await page.evaluate(()=>!!editor.scene),await page.locator('#house-stage').innerText());await action('edit').click();
  s=await snapshot();assert.equal(s.state.layer,'STRUCTURE');assert.equal(s.state.build,null);assert.equal(s.state.buildRotation,270);assert.equal(s.state.finish,'tile');assert.equal(s.state.color,'#123abc');
  await reset();assert.equal((await snapshot()).state.build,null);
  await page.screenshot({path:require('./test-artifacts.cjs')('roombloom-dock.png')});
  console.log('PASS R rotation and texture preferences persist, Type stays empty across layer changes, Save, reload and Reset');
  await action('type-menu').focus();await page.keyboard.press('ArrowUp');
  assert.equal(await page.evaluate(()=>document.activeElement.dataset.value),'floor');
  await page.keyboard.press('Enter');assert.equal((await snapshot()).state.build,'floor');
  await action('type-menu').focus();await page.keyboard.press('Escape');assert.equal(await action('type-menu').getAttribute('aria-expanded'),'false');
  await page.keyboard.press('Escape');assert.equal((await snapshot()).state.tool,'SELECT');
  assert.equal((await snapshot()).state.build,null);assert.equal(await action('type-menu').innerText(),'Type');
  await build('floor');await click(.5,.5);assert.equal((await snapshot()).house.structure.floors.length,1);
  assert.equal(await action('type-menu').innerText(),'Type');assert.equal((await snapshot()).state.build,null);
  await click(1.5,.5);assert.equal((await snapshot()).house.structure.floors.length,1);
  await build('floor');await click(.5,.5);assert.equal((await snapshot()).state.build,'floor');
  await page.keyboard.press('Escape');assert.equal(await action('type-menu').innerText(),'Type');
  console.log('PASS each build requires a new Type, invalid placement can retry and Escape clears it');
  const mobileState=await page.context().storageState();await page.close();
  const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true,storageState:mobileState});
  mobile.on('pageerror',error=>{errors.push(error.message);console.error('Mobile error:',error.message);});
  mobile.on('requestfailed',request=>{errors.push(request.url()+': '+request.failure()?.errorText);console.error('Mobile resource:',request.url(),request.failure());});
  await mobile.goto((process.env.ROOMBLOOM_URL||'http://127.0.0.1:8767')+'/#/room/test');
  await mobile.locator('[data-h-action="edit"]').tap().catch(async error=>{console.error('Mobile page:',mobile.url(),await mobile.locator('body').innerText());throw error;});
  assert.equal(await mobile.locator('[data-h-action="export"]').isVisible(),true);assert.equal(await mobile.locator('[data-h-action="import"]').isVisible(),true);
  await mobile.locator('[data-h-action="type-menu"]').tap();
  assert.equal(await mobile.locator('[data-h-action="type-menu"]').getAttribute('aria-expanded'),'true');
  assert.equal(await mobile.locator('#house-stage canvas').getAttribute('data-tool'),'select');
  await mobile.locator('[data-key="build"][data-value="wall"]').tap();
  assert.equal(await mobile.locator('#house-stage canvas').getAttribute('data-tool'),'place');
  assert.match(await mobile.locator('[data-h-action="type-menu"]').innerText(),/^Type: Wall/);
  await mobile.screenshot({path:require('./test-artifacts.cjs')('roombloom-touch-menu.png')});await mobile.close();
  console.log('PASS keyboard Type navigation and native touch Type/Save menus');
  assert.deepEqual(errors,[]);console.log('PASS no browser errors');
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
