/* User preset, bounded indoor shadows, explicit completion, appliance transitions and Pip controls. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-webgl','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'America/Vancouver'}),page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 const seed=()=>{if(!localStorage.getItem('roombloom-demo-v1'))localStorage.setItem('roombloom-demo-v1',JSON.stringify({version:1,loggedIn:true,user:{name:'Test'},rooms:[{id:'refine',name:'My room',code:'REFINE',members:[{id:'self'},{id:'alex',name:'Alex'}]}],connections:{},invitations:[]}));};
 try{
  await context.addInitScript(seed);
  await page.route('**/house/editor.js',r=>r.fulfill({contentType:'text/javascript',body:fs.readFileSync(path.join(__dirname,'../house/editor.js'),'utf8')+'\nconst mountOriginal=RoomBloomHouse.mount;RoomBloomHouse.mount=(...args)=>(window.editor=mountOriginal(...args));'}));
  await page.goto((process.env.ROOMBLOOM_URL||'http://127.0.0.1:8767')+'/#/room/refine');await page.waitForFunction(()=>window.editor?.scene);
  const act=n=>page.locator('[data-h-action="'+n+'"]'),close=()=>act('close-dialog').click(),open=type=>page.evaluate(type=>editor.interactions.open(editor.house.objects.find(o=>o.objectType===type)),type);
  const preset=JSON.parse(fs.readFileSync(path.join(__dirname,'../house/presets/default-house.json'),'utf8'));
  assert.deepEqual(await page.evaluate(()=>editor.house.structure),preset.structure);assert.equal(await page.evaluate(()=>editor.house.objects.length),preset.objects.length);assert.equal(await page.evaluate(()=>editor.house.objects.every(o=>Object.values(o.customState.machines||{}).every(bookings=>bookings.length===0))),true);
  assert.deepEqual(await page.evaluate(()=>editor.house.objects.map(o=>[o.id,o.objectType,o.grid,o.rotation])),preset.objects.map(o=>[o.id,o.objectType,o.grid,o.rotation]));
  await page.evaluate(()=>{editor.house.lighting={mode:'manual',level:.35};editor.applyLighting();editor.scene.render(editor.animal.view());});
  const exterior=await page.evaluate(()=>{const s=editor.scene,gl=s.renderer.getContext();s.scene.updateMatrixWorld(true);s.renderer.render(s.scene,s.camera);return [[6.5,3],[3,5.5],[6,5.5]].map(([x,z])=>{const p=new THREE.Vector3(x,0,z).project(s.camera),px=Math.floor((p.x+1)*s.canvas.width/2),py=Math.floor((p.y+1)*s.canvas.height/2),rgba=new Uint8Array(4);gl.readPixels(px,py,1,1,gl.RGBA,gl.UNSIGNED_BYTE,rgba);return{px,py,w:s.canvas.width,h:s.canvas.height,alpha:rgba[3]};});});
  for(const pixel of exterior){assert.ok(pixel.px>=0&&pixel.py>=0&&pixel.px<pixel.w&&pixel.py<pixel.h);assert.equal(pixel.alpha,0,'outside-floor pixels have no indoor-light shadow overlay');}
  assert.ok(await page.evaluate(()=>[...editor.scene.entries.values()].some(e=>e.lamp?.visible&&e.lamp.castShadow)));
  await page.mouse.move(200,80);await page.screenshot({path:require('./test-artifacts.cjs')('roombloom-bounded-lights.png')});console.log('PASS supplied default layout, fresh activity and transparent exterior with indoor shadows retained');
  await act('pet-status').click();assert.equal(await page.locator('[data-pip-volume]').inputValue(),'70');
  await page.locator('[data-pip-volume]').evaluate(el=>{el.value='35';el.dispatchEvent(new Event('input',{bubbles:true}));});assert.equal(await page.locator('[data-pip-volume-label]').innerText(),'35%');
  await page.evaluate(()=>{const bell=editor.tasks.bell,original=bell.meow.bind(bell);bell.meow=volume=>{window.lastMeow={volume,played:original(volume)};return window.lastMeow.played;};});
  await act('pip-preview').click();await page.waitForFunction(()=>window.lastMeow?.played);assert.equal(await page.evaluate(()=>window.lastMeow.volume),.35);
  await page.locator('[data-pip-mute]').check();assert.equal(await act('pip-preview').isDisabled(),true);assert.equal(await page.locator('[data-pip-volume]').isDisabled(),true);
  await page.locator('[data-pip-mute]').uncheck();await page.locator('[data-pip-volume]').evaluate(el=>{el.value='0';el.dispatchEvent(new Event('input',{bubbles:true}));});await act('pip-preview').click();assert.equal(await page.evaluate(()=>window.lastMeow.played),false);
  await page.locator('[data-pip-volume]').evaluate(el=>{el.value='80';el.dispatchEvent(new Event('input',{bubbles:true}));});await act('close-pet').click();await page.reload();await page.waitForFunction(()=>window.editor?.scene);assert.equal(await page.evaluate(()=>editor.tasks.meowVolume),.8);console.log('PASS meow volume, actual audio startup, preview, mute, zero volume and reload');
  await page.evaluate(()=>{window.clockNow=Date.now();Date.now=()=>window.clockNow;const h=editor.house,H=RoomBloomHouse;for(const type of ['oven','laundry'])if(!editor.house.objects.some(o=>o.objectType===type)){const free=editor.house.structure.floors.find(f=>!H.CollisionValidator.object(editor.house,H.objectDefinition(type,f.grid))&&H.GridSystem.key(f.grid)!==H.GridSystem.key(editor.house.animal.grid));editor.mutate(()=>editor.objects.place(type,{grid:free.grid},0,1.5),'Fixture');}editor.save();});
  for(const type of ['oven','laundry']){
   await open(type);const count=await page.locator('[data-h-form="laundry-book"]').count();
   for(let i=0;i<count;i++){
    const form=page.locator('[data-h-form="laundry-book"]').nth(i);assert.equal(await form.locator('[value="queue"]').isVisible(),false);await form.locator('[name="minutes"]').fill('43');await form.locator('[value="reserve"]').click();assert.equal(await form.locator('[value="reserve"]').isDisabled(),true);assert.equal(await form.locator('[value="queue"]').isVisible(),true);
    const machine=await form.locator('[name="machine"]').inputValue();assert.equal(await page.evaluate(({type,machine})=>editor.house.objects.find(o=>o.objectType===type).customState.machines[machine][0].startAt===Date.now(),{type,machine}),true,'default booking starts immediately');
    await form.locator('[name="memberId"]').selectOption('alex');await form.locator('[value="queue"]').click();assert.equal(await form.locator('[value="reserve"]').isDisabled(),true);
   }await close();
  }
  await open('oven');await page.locator('[data-h-action="laundry-cancel"]').first().click();assert.equal(await page.locator('[value="reserve"]').isEnabled(),true);assert.equal(await page.locator('[value="queue"]').isVisible(),false);
  await page.evaluate(()=>{window.clockNow+=43*60000;editor.updateRoomTime();});assert.equal(await page.locator('[value="reserve"]').isDisabled(),true);assert.equal(await page.locator('[data-booking-status]').innerText(),'Running');await close();console.log('PASS immediate reservations, queue-only busy states, cancellation and live start transitions on all appliances');
  await page.evaluate(()=>{for(const o of editor.house.objects)delete o.customState.machines;const H=RoomBloomHouse,h=editor.house,wall=h.structure.walls.find(w=>!h.structure.doors.some(d=>d.wallId===w.id)&&!h.objects.some(o=>o.attachedWallId===w.id));editor.mutate(()=>{const b=editor.objects.place('board',{grid:wall.grid,wallId:wall.id},0,1.5);H.HouseFeatures.addTask(b,'Click to finish',['self','alex'],Date.now()+10000,editor.options.members);},'Task fixture');editor.save();});
  const card=page.locator('.house-task-card').first();const r=await card.boundingBox();await page.mouse.move(r.x+r.width/2,r.y+r.height/2);await page.mouse.down();await page.mouse.move(r.x-12,r.y+r.height/2,{steps:8});await page.mouse.up();assert.equal(await page.evaluate(()=>editor.tasks.items.some(t=>t.title==='Click to finish')),true);assert.equal(await card.evaluate(el=>getComputedStyle(el).cursor),'pointer');
  await card.click();assert.doesNotMatch(await page.locator('#house-dialog').innerText(),/swipe/i);await act('personal-complete').click();assert.equal(await page.evaluate(()=>editor.tasks.items.some(t=>t.title==='Click to finish')),false);assert.equal(await page.evaluate(()=>RoomBloomHouse.HouseTasks.forMember(editor.house,'alex').some(t=>t.title==='Click to finish')),true);
  await act('arrangement').click();assert.doesNotMatch(await page.locator('.house-agenda').innerText(),/Feed Pip/);
  await page.evaluate(()=>{editor.house.animal.lastFedAt=Date.now()-12*3600000;editor.updateRoomTime();});assert.match(await page.locator('.house-agenda').innerText(),/Feed Pip/);
  await page.evaluate(()=>{editor.house.animal.lastFedAt=Date.now()-18*3600000;editor.updateRoomTime();});assert.match(await page.locator('.house-agenda').innerText(),/Feed Pip/);
  await page.evaluate(()=>{editor.house.animal.lastFedAt=Date.now();editor.updateRoomTime();});assert.doesNotMatch(await page.locator('.house-agenda').innerText(),/Feed Pip/);await close();console.log('PASS no swipe completion, explicit per-person completion and live hungry-only feeding entry');
  await act('edit').click();await act('new-house').click();await page.locator('[data-h-action="reset-house"][data-value="basic"]').click();assert.deepEqual(await page.evaluate(()=>editor.house.structure),preset.structure);assert.equal(await page.evaluate(()=>editor.house.objects.length),preset.objects.length);await act('save').click();await page.reload();await page.waitForFunction(()=>window.editor?.scene);assert.equal(await page.evaluate(()=>editor.house.objects.length),preset.objects.length);
  await page.setViewportSize({width:390,height:844});await act('pet-status').click();await page.screenshot({path:require('./test-artifacts.cjs')('roombloom-pip-volume-mobile.png')});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  const filePage=await context.newPage();await filePage.goto('file://'+path.resolve(__dirname,'../index.html')+'#/room/refine');await filePage.waitForSelector('#house-stage canvas');assert.equal(await filePage.evaluate(()=>RoomBloomHouse.HouseModel.defaultHouse().objects.length),preset.objects.length);await filePage.close();
  assert.deepEqual(errors,[]);console.log('PASS new default Reset/reload, mobile volume panel and file:// startup');
 }catch(e){await page.screenshot({path:require('./test-artifacts.cjs')('roombloom-refinements-failure.png')});console.error(await page.locator('#house-dialog').innerText());throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
