(() => {
  'use strict';
  const D=window.BloomDesign;
  const KEY = 'roombloom-demo-v1';
  let houseRuntime = null;
  const app = document.getElementById('app');
  const modal = document.getElementById('modal');
  let storageWarning = '', returnAfterLogin = '', toastTimer, lastFocus, resettingDemo=false;
  const blank = () => ({version:1, loggedIn:false, user:{name:'', campus:'', habits:null}, rooms:[], connections:{}, invitations:[], lastRoom:null});
  let state = blank();
  try {
    const saved = JSON.parse(localStorage.getItem(KEY) || 'null');
    if (saved && saved.version === 1 && saved.user && Array.isArray(saved.rooms) && saved.connections && Array.isArray(saved.invitations)) state = saved;
    else if (saved) storageWarning = 'This demo could not read the previous save. A fresh session is ready.';
  } catch (_) { storageWarning = 'Browser storage is unavailable or the save is unreadable. This session still works, but changes may not survive a reload.'; }
  state.archives=Array.isArray(state.archives)?state.archives:[];
  const esc = value => String(value == null ? '' : value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const icons = {
    sprout:'<path d="M12 22V12M12 16C3 16 2 7 4 6c8-1 10 6 8 10ZM12 11c-1-7 4-10 9-9 1 6-3 11-9 9Z"/>',
    home:'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1Z"/><path d="M9 21v-8h6v8"/>',
    people:'<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M16 5a3 3 0 0 1 0 6M18 15a5 5 0 0 1 3 4v2"/>',
    plus:'<path d="M12 5v14M5 12h14"/>', back:'<path d="m14 6-6 6 6 6"/>',
    key:'<circle cx="8" cy="8" r="5"/><path d="m12 12 9 9m-3-3 3-3m-6 0 3-3"/>',
    folder:'<path d="M3 6h7l2 3h9v11H3Z"/>',
    check:'<path d="m5 12 4 4L19 6"/>', close:'<path d="m6 6 12 12M18 6 6 18"/>',
    info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7h.01"/>',
    task:'<rect x="5" y="4" width="15" height="17" rx="2"/><path d="m8 10 2 2 4-4M8 16h8"/>',
    board:'<rect x="3" y="4" width="18" height="14" rx="2"/><path d="M8 21v-3m8 3v-3M7 9h10M7 13h6"/>',
    copy:'<rect x="8" y="8" width="12" height="13" rx="2"/><path d="M16 8V3H3v13h5"/>',
    leaf:'<path d="M20 3C6 1 1 9 6 16s17 0 14-13ZM5 21 16 9"/>',
    clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/>',
    logout:'<path d="M9 3H3v18h6M8 12h13m-4-4 4 4-4 4"/>',
    trash:'<path d="M3 6h18M6 6l1 15h10l1-15M9 6V3h6v3M10 10v7m4-7v7"/>',
    calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4m10-4v4M3 11h18m-14 4h2m3 0h2m3 0h1M7 18h2m3 0h2"/>',
    resetAngle:'<path d="M3 11a9 9 0 1 1 2.6 7M3 4v7h7"/>',
    camera:'<path d="M3 7h4l2-3h6l2 3h4v13H3Z"/><circle cx="12" cy="13" r="4"/>',
    help:'<circle cx="12" cy="12" r="9"/><path d="M9.5 8a2.5 2.5 0 0 1 5 0c0 2-2.5 2-2.5 4M12 16h.01"/>',
    gear:'<path d="m9 3-.6 2.3-2 .9L4.3 6l-2 3.5L4 11v2l-1.7 1.5 2 3.5 2.1-.2 2 .9L9 21h6l.6-2.3 2-.9 2.1.2 2-3.5L20 13v-2l1.7-1.5-2-3.5-2.1.2-2-.9L15 3Z"/><circle cx="12" cy="12" r="3"/>',
    cat:'<path d="M4 10V3l5 4a12 12 0 0 1 6 0l5-4v7c4 9-1 11-8 11S0 19 4 10Z"/><path d="M8 12h.01M16 12h.01m-5 3 1 1 1-1M1 14l5 1m-5 3 5-1m12-2 5-1m-5 3 5 1"/>',
    edit:'<path d="m4 16-1 5 5-1L21 7l-4-4ZM14 6l4 4"/>',
    heart:'<path d="M12 21 3 12C-2 5 7-1 12 6c5-7 14-1 9 6Z"/>'
  };
  const icon = name => `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${icons[name] || icons.home}</svg>`;
  const initials = name => (name || '?').trim().split(/\s+/u).map(p=>Array.from(p)[0]).slice(0,2).join('').toUpperCase();
  const avatar = (name, cls='') => `<span class="avatar ${cls}">${esc(initials(name))}</span>`;
  const people = [
    {id:'jordan',name:'Jordan Lee',pronouns:'they/them',campus:'Design student',area:'Near campus',budget:1050,move:'November',color:'sage',sleep:'Early bird',clean:'Tidy daily',noise:'Quiet evenings',guests:'Occasionally',pets:'No pets',bio:'Usually up for a farmers’ market trip, a new recipe, or a quiet night with a sketchbook.',tags:['Cooking','Design','Weekend markets']},
    {id:'alex',name:'Alex Chen',pronouns:'he/him',campus:'Computer science student',area:'Downtown',budget:1200,move:'November',color:'peach',sleep:'Night owl',clean:'Weekly reset',noise:'Headphones on',guests:'Occasionally',pets:'Pet friendly',bio:'I like a clean kitchen, late-night coding with headphones, and a good shared grocery list.',tags:['Gaming','Bouldering','Coffee']},
    {id:'riley',name:'Riley Brooks',pronouns:'she/her',campus:'Environmental studies',area:'Near campus',budget:950,move:'December',color:'blue',sleep:'Flexible',clean:'Tidy daily',noise:'Some background music',guests:'Often',pets:'Pet friendly',bio:'Plant collector and trail enthusiast. Looking for a friendly home where we can communicate openly.',tags:['Plants','Hiking','Baking']},
    {id:'taylor',name:'Taylor Morgan',pronouns:'they/them',campus:'Early-career designer',area:'Westside',budget:1400,move:'December',color:'lilac',sleep:'Early bird',clean:'Weekly reset',noise:'Quiet evenings',guests:'Rarely',pets:'No pets',bio:'Early work mornings, Sunday meal prep, and a calm place to unwind. Happy to share a cup of tea.',tags:['Reading','Cycling','Tea']}
  ];
  const samples = [
    {id:'sample-maple',name:'Maple House',code:'RB42',members:[{id:'sam',name:'Sam',color:'peach'},{id:'alex-home',name:'Alex',color:'blue'}],sample:true},
    {id:'sample-sunlit',name:'Sunlit Loft',code:'SUNNY3',members:[{id:'lee',name:'Lee',color:'sage'},{id:'noah',name:'Noah',color:'peach'},{id:'ava',name:'Ava',color:'lilac'}],sample:true},
    {id:'sample-cedar',name:'Cedar House',code:'FULL4',members:[{id:'a',name:'Ari'},{id:'b',name:'Blair'},{id:'c',name:'Casey'},{id:'d',name:'Drew'}],sample:true}
  ];
  const plant = () => `<svg class="plant" viewBox="0 0 110 140" aria-hidden="true"><path d="M55 90V38" stroke="#326344" stroke-width="5"/><path d="M55 66C12 72 10 31 21 28c28-5 40 14 34 38Z" fill="#789960" stroke="#326344" stroke-width="2"/><path d="M55 48C44 16 65 0 87 7c15 26-10 45-32 41Z" fill="#aac387" stroke="#326344" stroke-width="2"/><path d="m22 87 8 43h51l8-43Z" fill="#dcaa77" stroke="#754d36" stroke-width="2"/><rect x="18" y="83" width="75" height="13" rx="5" fill="#efc999" stroke="#754d36" stroke-width="2"/><circle cx="44" cy="108" r="2.4" fill="#453f2c"/><circle cx="68" cy="108" r="2.4" fill="#453f2c"/><path d="M50 116q6 5 12 0" stroke="#453f2c" stroke-width="2" fill="none"/></svg>`;
  const roomArt = () => `<svg viewBox="0 0 680 440" role="img" aria-label="An illustrated shared living room with a sofa, a house board, a little plant and warm afternoon light"><defs><pattern id="floor" width="55" height="32" patternUnits="userSpaceOnUse"><path d="M0 31h55M27 0v31" stroke="#bcb994" stroke-width="1" opacity=".5"/></pattern></defs><path d="M58 320V67l290-32 274 89v207l-274 85Z" fill="#e1d8b9"/><path d="m58 320 290 96 274-85-274-86Z" fill="#d5c7a3"/><path d="m58 320 290 96 274-85-274-86Z" fill="url(#floor)"/><path d="M58 67 348 35v210L58 320Z" fill="#e9e8d1"/><path d="m348 35 274 89v207l-274-86Z" fill="#d9dfc5"/><path d="M102 95 235 81v118l-133 25Z" fill="#adc3b0" stroke="#6c8063" stroke-width="7"/><path d="m109 99 120-12v105l-120 23Z" fill="#dbece1"/><path d="m171 93 1 111m-63-55 121-16" stroke="#fff8df" stroke-width="7"/><path d="m111 198 39-40 30 20 46-56v69Z" fill="#b6c9a3"/><path d="m262 94 66-8v81l-66 13Z" fill="#b8a078" stroke="#8c7e60" stroke-width="4"/><path d="m270 108 21-3v29l-21 3m31-31 17-2v20l-17 3" fill="#fff7db"/><path d="m278 142 37-6v20l-37 5Z" fill="#e6b39d"/><ellipse cx="363" cy="326" rx="145" ry="44" fill="#bbb58c"/><ellipse cx="363" cy="326" rx="131" ry="35" fill="#e9dfb9"/><path d="m113 249 98-28 113 36v56l-98 31-113-37Z" fill="#6c805b" stroke="#526747" stroke-width="2"/><path d="m122 243 89-23 104 32-90 28Z" fill="#abc097"/><path d="m122 245 2-54q1-12 12-11l69 17q13 3 13 17v62Z" fill="#94ad7d"/><path d="m211 204 83 26q12 4 12 18v28l-86-1Z" fill="#a9be94"/><path d="m112 252 12-7 103 32-1 39-112-35Z" fill="#8da372"/><path d="m224 278 91-26 12 13v47l-101 30Z" fill="#7b9365"/><path d="m144 218 29 8 9 38-37-11Z" fill="#ecd7a1"/><path d="m239 233 30 9 6 30-34-2Z" fill="#d7b49e"/><path d="m139 309 0 23m159-7v18" stroke="#554c35" stroke-width="8"/><path d="m406 157 60 18v111l-60-19Z" fill="#f1edda" stroke="#9b9f86" stroke-width="3"/><path d="m406 205 60 18m-49-38v11m0 35v15" stroke="#84917b" stroke-width="3"/><path d="m528 230 0-93m-25 95h50" stroke="#77674b" stroke-width="4"/><path d="m506 119 43 12 13 38-73-21Z" fill="#f3d892" stroke="#ab9864" stroke-width="2"/><ellipse cx="390" cy="310" rx="46" ry="16" fill="#988660"/><path d="m370 310-5 39m42-38 4 37" stroke="#877153" stroke-width="5"/><ellipse cx="390" cy="302" rx="47" ry="16" fill="#ddbd85" stroke="#aa936a" stroke-width="2"/><g transform="translate(354 219) scale(.66)">${plant().replace(/<svg[^>]*>|<\/svg>/g,'')}</g><path d="m550 291 29 8-3 38-23-7Z" fill="#87977c" stroke="#5f755b" stroke-width="2"/><path d="m547 288 36 11" stroke="#586c51" stroke-width="4"/><path d="m489 339 21 6-3 18-17-5Z" fill="#b0815c"/><path d="m499 340 1-36m0 18q-21 0-16-16 14-2 16 16m0-7q20 0 19-16-18 0-19 16" fill="#6c8b55" stroke="#547645" stroke-width="2"/></svg>`;
  const peopleArt = () => `<svg viewBox="0 0 210 180" aria-hidden="true"><circle cx="116" cy="89" r="72" fill="#eed996"/><path d="M35 174v-38q0-25 30-25t30 25v38" fill="#799878"/><circle cx="65" cy="85" r="26" fill="#dbb191"/><path d="M39 85q-9-41 26-36 31 0 27 38l-12-22-30 11Z" fill="#4e5140"/><path d="M100 180v-46q0-24 30-24t30 24v46" fill="#bd7557"/><circle cx="130" cy="85" r="26" fill="#f1ceaa"/><path d="M105 78q-7-38 26-33 35 2 23 38l-6-21-21 9Z" fill="#5b453a"/><circle cx="60" cy="87" r="2" fill="#493d32"/><circle cx="74" cy="87" r="2" fill="#493d32"/><path d="M61 98q6 4 11 0m51 0q6 4 11 0" stroke="#73563b" fill="none" stroke-width="2"/><circle cx="123" cy="87" r="2" fill="#493d32"/><circle cx="138" cy="87" r="2" fill="#493d32"/><path d="m167 112 7 5 7-5-7 15Z" fill="#fff6d8"/></svg>`;
  function save(){try{localStorage.setItem(KEY,JSON.stringify(state));return true;}catch(_){storageWarning='Your browser could not save changes. They are available for this session only.';showToast(storageWarning);return false;}}
  function route(){const raw=location.hash.replace(/^#/, '') || '/';const [path,q='']=raw.split('?');return {path,params:new URLSearchParams(q)};}
  function go(path){if(location.hash === '#'+path) render();else location.hash=path;}
  function showToast(text){clearTimeout(toastTimer);const el=document.getElementById('toast');el.textContent=text;el.classList.add('visible');toastTimer=setTimeout(()=>el.classList.remove('visible'),4200);}
  function memberName(m){return m.id==='self'?state.user.name:m.name;}
  function rooms(){return state.rooms.filter(r=>Array.isArray(r.members)&&r.members.some(m=>m.id==='self'));}
  function room(id){return rooms().find(r=>r.id===id);}
  function directory(){const map=new Map(samples.map(r=>[r.id,r]));state.rooms.forEach(r=>map.set(r.id,r));return [...map.values()];}
  function person(id){return people.find(p=>p.id===id);}
  function copyButton(value,label='Copy invite code'){return `<button class="btn secondary small" data-action="copy" data-value="${esc(value)}">${icon('copy')}${esc(label)}</button>`;}
  function header(){return `<header class="topbar"><button class="brand" data-go="/" aria-label="Bloom Room welcome" title="Back to welcome">${D.house()}<span>Bloom Room</span></button><div class="header-actions">${state.loggedIn?D.moodSelect()+`<button class="profile-button" data-go="/profile" aria-label="My profile">${D.art('star')}<span>My Profile</span>${D.art('star')}</button>`:''}</div></header>`;}
  function shell(body){return `${state.loggedIn?header():''}${storageWarning?`<div class="storage-banner info-box warning" role="status">${esc(storageWarning)}</div>`:''}<main class="main" id="main" tabindex="-1">${body}</main>${state.loggedIn?`<footer class="footer"><span>A little more together.</span><button data-action="about">About this local demo</button></footer>`:''}`;}
  function back(to,label='Back'){return `<button class="back" data-go="${esc(to)}">${icon('back')}${esc(label)}</button>`;}
  function intro(eye,title,sub,action=''){return `<div class="page-intro"><div><div class="eyebrow">${esc(eye)}</div><h1>${esc(title)}</h1>${sub?`<p class="subheading">${esc(sub)}</p>`:''}</div>${action}</div>`;}
  function field(id,label,options){return `<div class="form-field"><label for="${id}">${esc(label)}</label>${options}</div>`;}
  function errorSlot(){return '<p class="form-error" id="form-error" role="alert" tabindex="-1"></p>';}
  function formError(form,text,id){const el=form.querySelector('.form-error');el.textContent=text;if(id){const input=form.elements[id];if(input){input.setAttribute('aria-invalid','true');input.setAttribute('aria-describedby','form-error');input.focus();return;}}el.focus();}
  function miniMembers(r){return `<div class="mini-members">${r.members.map(m=>avatar(memberName(m),m.color||'sage')).join('')}</div>`;}
  function homeCard(r,archived=false){return `<article class="room-tile"><button class="room-tile-main" data-action="house-preview" data-id="${esc(r.id)}" data-archive="${archived}" aria-label="Preview ${esc(r.name)}">${D.house()}<h3>${esc(r.name)}</h3><span>${archived?'A home in your story':r.members.length+' / 4 roomies'}</span></button>${!archived?`<button class="archive-link" data-action="archive-room" data-id="${esc(r.id)}">Leave & archive</button>`:`<small>Left ${esc(new Date(r.archivedAt).toLocaleDateString([], {month:'short',day:'numeric'}))}</small>`}</article>`;}
  function loginView(){return `<section class="welcome-stage" aria-label="Welcome to Bloom Room"><button class="intro-skip" data-action="skip-intro">Skip to login ↗</button><button class="intro-replay" data-action="replay-intro" hidden>Replay the welcome ↺</button><div class="our-home" aria-hidden="true">${D.art('star')}<span>Our Home</span>${D.art('bow')}</div><div class="bloom-lockup"><h1><span>Bloom</span>${D.art('bow')}<span>Room</span></h1><div class="bloom-submark"><span>Our</span>${D.house()}<span>Home</span></div></div><div class="login-star star-left">${D.art('star')}</div><div class="login-star star-right">${D.art('star')}</div><div class="login-entry"><form id="login-form" novalidate><label for="name">Please log in with your ID</label><div class="login-line"><input id="name" name="name" autocomplete="username" aria-label="Your ID" placeholder="Your ID" maxlength="32" value="${esc(state.user.name)}" required><button type="submit" aria-label="Log in">↗</button></div>${errorSlot()}</form><p class="login-local-note">Just your ID for now. Your home stays in this browser.</p></div><div class="flying-key">${D.art('key')}</div><span class="intro-page-note" aria-hidden="true">a small beginning, a shared home</span></section>`;}
  function hubMode(path){return path==='/homes'?'homes':path==='/find'?'find':path==='/'||path==='/login'?'welcome':null;}
  function welcomeView(mode='welcome'){
    const panels={
      welcome:`<div class="welcome-bottom"><p>${D.art('star')}A place to be yourself.<br>A little room for each other.</p><p>Your next chapter starts here</p></div>`,
      homes:`<div class="gateway-row"><nav class="gateway-options" aria-label="My community">${[['/create','Create a Room','naming our shared space'],['/join','Join a Room','Have an invite link? Come on in'],['/load','Load your Room','view saved rooms']].map(([url,title,note])=>`<button class="gateway-choice" data-go="${url}"><strong>${title}</strong><span>${note}</span></button>`).join('')}</nav><p class="gateway-key">Make a little room.</p></div>`,
      find:`<div class="gateway-row find-gateway"><p class="gateway-key">Your people are out there.</p><nav class="gateway-options" aria-label="Find a roommate"><button class="gateway-choice" data-go="/habits"><strong>Survey</strong><span>Refine my habits</span></button><button class="gateway-choice" data-go="/plaza"><strong>Roommate Plaza</strong><span>Browse potential roomies</span></button></nav></div><p class="demo-footnote">A little local demo · Meet fictional people, try real interactions.</p>`
    };
    return `<section class="welcome-page" data-hub-mode="${mode}"><div class="welcome-greeting"><h1>Hi, ${esc(state.user.name)} : )</h1><p>Welcome ! Home starts with right people</p></div><div class="welcome-choices"><button class="journey-choice${mode==='homes'?' is-current':''}" data-go="/homes" aria-controls="hub-homes" aria-expanded="${mode==='homes'}"><span class="pill">Already have your people?</span><h2>My Community</h2><p>Create / Join / archive<br>A SHARED ROOM</p><span class="choice-arrow" aria-hidden="true">↗</span></button><button class="journey-choice${mode==='find'?' is-current':''}" data-go="/find" aria-controls="hub-find" aria-expanded="${mode==='find'}"><span class="pill">Room for someone new</span><h2>Find a Roommate</h2><p>Let’s meet your roomies!</p><span class="choice-arrow" aria-hidden="true">↗</span></button></div><div class="welcome-details">${Object.entries(panels).map(([key,body])=>`<div id="hub-${key}" data-hub-panel="${key}"${mode===key?'':' hidden'}>${body}</div>`).join('')}</div></section>`;
  }
  function homesView(){return welcomeView('homes');}
  function communityPage(trail,title,description,body,{to='/homes',label='My Community',wide=false}={}){
    const location=`<nav class="form-breadcrumbs" aria-label="Page location"><ol>${trail.map((step,i)=>`<li${i===trail.length-1?' aria-current="page"':''}>${i?'<span aria-hidden="true">/</span> ':''}${esc(step)}</li>`).join(' ')}</ol></nav>`;
    return `<div class="community-page${wide?' community-wide':''}">${back(to,label)}${location}<section class="community-paper"><header class="community-heading"><div><h1>${esc(title)}</h1><p class="subheading">${esc(description)}</p></div>${D.house('community-mark')}</header>${body}</section></div>`;
  }
  function createView(){return communityPage(['Create','Room details'],'Name your home.','A little space for you and your people.',`<form id="create-form" class="community-form" novalidate>${field('roomName','House name','<input id="roomName" name="roomName" maxlength="40" placeholder="Our little home" aria-describedby="create-hint" required>')}<p class="help" id="create-hint">Up to four roommates. You can invite them after you move in.</p>${errorSlot()}<div class="community-actions"><button type="submit" class="btn">Create & enter room ${icon('plus')}</button></div></form><div class="community-footnote"><span>Already have an invite?</span><button class="text-link" data-go="/join">Join a room ↗</button></div>`);}
  function joinView(params){return communityPage(['Join','Invitation'],'Join your people.','Your shared home is just an invitation away.',`<form id="join-form" class="community-form" novalidate>${field('invite','Invite code, link, or room name',`<input id="invite" name="invite" value="${esc(params.get('code')||'')}" autocomplete="off" placeholder="e.g. RB42" aria-describedby="join-hint" required>`)}<p class="help" id="join-hint">We’ll show you the room and its people before you join.</p>${errorSlot()}<div class="community-actions"><button class="btn" type="submit">Find my room <span aria-hidden="true">↗</span></button></div></form><details class="sample-invites"><summary>Need an invite? Try a demo home</summary><div class="sample-home-list">${samples.map(r=>`<button type="button" data-action="fill-invite" data-value="${r.code}"><span><strong>${esc(r.name)}</strong><small>${4-r.members.length?4-r.members.length+' open seat'+(r.members.length===3?'':'s'):'Room is full'}</small></span><span class="sample-code">${r.code} ↗</span></button>`).join('')}</div><p class="help">Demo rooms are available only in this browser.</p></details>`);}
  function memberGrid(r,empty=false){const list=r.members.map(m=>`<div class="member">${avatar(memberName(m),m.color||'sage')}<div><div class="name">${esc(memberName(m))}</div><p class="small">${m.id==='self'?'You':(m.demo?'Demo roommate':'Sample roommate')}</p></div></div>`);if(empty)for(let i=r.members.length;i<4;i++)list.push(`<div class="member empty"><span class="avatar">${icon('plus')}</span><div><div class="name">Open seat</div><p class="small">Room for a roommate</p></div></div>`);return `<div class="member-list">${list.join('')}</div>`;}
  function previewView(id){const r=directory().find(r=>r.id===id);if(!r)return notFound('That room could not be found.','/join');const joined=!!room(id);return communityPage(['Join','Room preview'],'Is this your home?','Meet the people who make it a home.',`<div class="community-room-heading"><h2 class="break">${esc(r.name)}</h2><span class="pill">${r.members.length} / 4 roomies</span></div>${memberGrid(r,true)}<p class="help">${joined?'You already belong here. Open your room to continue.':'Joining adds your display name to this room in the local demo.'}</p><p class="form-error" id="join-error" role="alert"></p><div class="community-actions">${joined?`<button class="btn" data-go="/room/${esc(id)}">Open room ↗</button>`:r.members.length>=4?`<span class="pill warm">This room is full</span><button class="btn" data-go="/join">Try another room</button>`:`<button class="btn" data-action="confirm-join" data-id="${esc(id)}">Join ${esc(r.name)} ↗</button>`}<button class="text-link" data-go="/join">This isn’t my room</button></div>`,{to:'/join',label:'Find a room'});}
  function loadView(params=new URLSearchParams()){const archived=params.get('tab')==='archive',list=archived?state.archives:rooms();return communityPage(['Collection',archived?'Archive':'My rooms'],archived?'Homes in your story.':'A place to come back to.',archived?'Little places. Lovely chapters.':'Open a home to take a look inside.',`<div class="collection-toolbar"><nav class="archive-tabs" aria-label="Room collection"><button data-go="/load" aria-current="${!archived?'page':'false'}">My rooms <span>${rooms().length}</span></button><button data-go="/load?tab=archive" aria-current="${archived?'page':'false'}">Archive <span>${state.archives.length}</span></button></nav><button class="text-link" data-go="/create">+ Create a room</button></div>${list.length?`<div class="house-shelf">${list.map(r=>homeCard(r,archived)).join('')}</div>`:`<div class="archive-empty">${D.house()}<h2>${archived?'A little space for memories.':'Your home is waiting.'}</h2><p>${archived?'Homes you leave will stay here, with a last look inside.':'Create your first shared space, or come in with an invite.'}</p>${archived?'':`<div class="community-actions"><button class="btn" data-go="/create">Create a room</button><button class="text-link" data-go="/join">Join with an invite ↗</button></div>`}</div>`}`,{wide:true});}
  function findView(){return welcomeView('find');}
  const habitFields=[['sleep','Your daily rhythm',['Early bird','Night owl','Flexible']],['clean','Your cleaning rhythm',['Tidy daily','Weekly reset','Flexible']],['noise','Sound at home',['Quiet evenings','Headphones on','Some background music']],['guests','Having guests over',['Rarely','Occasionally','Often']],['pets','Pets in the home',['Pet friendly','No pets','Open to discussing']]];
  function habitsView(){const h=state.user.habits||{};return communityPage(['Survey','Habit'],'At home, in your own way.','Little details make a happy home. Let’s find your rhythm.',`<form id="habits-form" class="community-form"><div class="habit-grid">${habitFields.map(([key,label,opts])=>`<div class="house-question">${D.house('question-mark')}${field(key,label,`<select id="${key}" name="${key}"><option value="">Prefer to discuss</option>${opts.map(o=>`<option${h[key]===o?' selected':''}>${esc(o)}</option>`).join('')}</select>`)}</div>`).join('')}<div class="house-question">${D.house('question-mark')}${field('budget','Monthly rent budget (CAD)',`<select id="budget" name="budget"><option value="">Prefer to discuss</option>${[1000,1200,1500].map(n=>`<option value="${n}"${h.budget===String(n)?' selected':''}>Up to $${n.toLocaleString()}</option>`).join('')}</select>`)}</div><div class="house-question">${D.house('question-mark')}${field('preferences','A little more about my preferences',`<input id="preferences" name="preferences" maxlength="240" placeholder="The little things that matter to you" value="${esc(h.preferences||'')}">`)}</div></div>${errorSlot()}<div class="community-actions"><button class="btn" type="submit">Save living habits</button><button class="text-link" type="button" data-go="/plaza">Browse without saving ↗</button></div></form>`,{to:'/find',label:'Find a Roommate'});}
  function personCard(p){const connected=state.connections[p.id];return `<article class="panel person-card"><div class="person-top">${avatar(p.name,p.color+' lg')}<div><h2>${esc(p.name)}</h2><p class="small" style="margin:4px 0 0">${esc(p.campus)}</p></div></div><div class="chip-list"><span class="pill">${esc(p.sleep)}</span><span class="pill">${esc(p.pets)}</span>${connected?`<span class="pill green">${esc(connected==='accepted'?'Connected':connected==='pending'?'Request pending':'Request declined')}</span>`:''}</div><p>${esc(p.bio)}</p><div class="split-row small" style="margin-bottom:18px"><strong>CAD ${p.budget.toLocaleString()} / mo</strong><span class="muted">${esc(p.area)}</span></div><button class="btn secondary" data-go="/person/${p.id}">View profile</button></article>`;}
  function plazaResults(q='',rhythm='',budget=''){const list=people.filter(p=>(!q||`${p.name} ${p.bio} ${p.area} ${p.tags.join(' ')}`.toLowerCase().includes(q.toLowerCase()))&&(!rhythm||p.sleep===rhythm)&&(!budget||p.budget<=Number(budget)));return `${list.length?`<div class="grid-two">${list.map(personCard).join('')}</div>`:`<div class="panel empty-state"><span class="house-symbol">${icon('people')}</span><h2>No sample profiles match.</h2><p>Try a different name, a higher budget, or all daily rhythms.</p><button class="btn secondary" data-action="clear-filters">Clear filters</button></div>`}<p class="help mt" role="status">${list.length} fictional profile${list.length===1?'':'s'} · No real matching or messaging</p>`;}
  function plazaView(params){const q=params.get('q')||'',rhythm=params.get('rhythm')||'',budget=params.get('budget')||'';return `${back('/find','Find a roommate')}${intro('ROOMMATE PLAZA','A few people to meet.','Explore the everyday details before deciding to share a home.',`<button class="btn secondary" data-go="/habits">${icon('leaf')}My living habits</button>`)}<form class="filters" id="filters-form">${field('search','Search profiles',`<input id="search" name="q" type="search" placeholder="Name, interest, or area" value="${esc(q)}">`)}${field('rhythm','Daily rhythm',`<select id="rhythm" name="rhythm"><option value="">All rhythms</option>${['Early bird','Night owl','Flexible'].map(v=>`<option${rhythm===v?' selected':''}>${v}</option>`).join('')}</select>`)}${field('max-budget','Max. monthly rent',`<select id="max-budget" name="budget"><option value="">Any budget</option>${[1000,1200,1500].map(n=>`<option value="${n}"${budget===String(n)?' selected':''}>CAD ${n.toLocaleString()}</option>`).join('')}</select>`)}<button class="btn secondary" type="submit">Apply filters</button></form><div id="plaza-results">${plazaResults(q,rhythm,budget)}</div>`;}
  function personView(id){const p=person(id);if(!p)return notFound('This demo profile does not exist.','/plaza');const status=state.connections[id],shared=rooms().find(r=>r.members.some(m=>m.id===id));let action;
    if(shared)action=`<div class="info-box success">You share ${esc(shared.name)}.</div><button class="btn full mt" data-go="/room/${shared.id}">Open shared room</button>`;
    else if(status==='accepted')action=`<div class="info-box success">Connection accepted in the demo.</div><p class="mt">Ready to explore living together? Choose a room to invite ${esc(p.name.split(' ')[0])} into.</p><button class="btn full mt" data-go="/invite/${id}">Invite to a room</button>`;
    else if(status==='pending')action=`<div class="info-box">Request pending. Nobody has been contacted.</div><p class="small mt">Choose a simulated response to continue the prototype.</p><button class="btn full mt" data-action="respond" data-id="${id}" data-value="accepted">Simulate acceptance</button><button class="btn secondary full mt-sm" data-action="respond" data-id="${id}" data-value="declined">Simulate decline</button><button class="btn text" data-action="cancel-request" data-id="${id}">Cancel request</button>`;
    else if(status==='declined')action=`<div class="info-box warning">This demo request was declined.</div><button class="btn full mt" data-go="/plaza">Meet someone else</button><button class="btn text" data-action="request" data-id="${id}">Try this demo again</button>`;
    else action=`<p>Say hello and see if you’d like to share a home.</p><button class="btn full mt" data-action="request" data-id="${id}">Request connection</button><p class="help mt">Demo only. The next step lets you simulate their response.</p>`;
    return `${back('/plaza','Roommate Plaza')}<div class="profile-layout"><section class="panel"><div class="profile-hero">${avatar(p.name,p.color+' xl')}<div><div class="sample-label">Fictional profile</div><h1 class="mt-sm">${esc(p.name)}</h1><p class="mt-sm">${esc(p.pronouns)} · ${esc(p.campus)}</p></div></div><p>${esc(p.bio)}</p><div class="chip-list mt">${p.tags.map(t=>`<span class="pill">${esc(t)}</span>`).join('')}</div><hr class="separator"><h2>Life at home</h2><div class="habit-facts mt">${habitFields.map(([key,label])=>`<div class="fact"><div class="label">${esc(label)}</div><div class="value">${esc(p[key])}</div></div>`).join('')}<div class="fact"><div class="label">Monthly rent budget</div><div class="value">CAD ${p.budget.toLocaleString()}</div></div></div><p class="help mt">${esc(p.area)} · Looking to move in ${esc(p.move)}</p></section><aside class="panel side-sticky"><h2 class="inline-icon">${icon('people')}A possible roommate</h2><div class="mt">${action}</div><hr class="separator"><h3>Talk it through</h3><p class="small mt-sm">Cleaning, shared costs, guests, and quiet hours are worth agreeing on together.</p></aside></div>`;
  }
  function inviteView(id,params){const p=person(id);if(!p||state.connections[id]!=='accepted')return notFound('Connect with this person before inviting them.','/plaza');const own=rooms(),mode=params.get('mode')||(own.length?'existing':'new');const pending=state.invitations.find(i=>i.personId===id&&i.status==='pending');if(pending)return invitationView(pending.id);return communityPage(['Invite',mode==='new'?'New room':'Existing room'],`Invite ${p.name.split(' ')[0]}.`,'Choose a familiar home, or start a new chapter together.',`<div class="mode-choice"><button class="btn secondary" aria-pressed="${mode==='existing'}" data-go="/invite/${id}?mode=existing">Existing room</button><button class="btn secondary" aria-pressed="${mode==='new'}" data-go="/invite/${id}?mode=new">New room</button></div><form id="invite-form" class="community-form" data-person="${id}" data-mode="${mode}" novalidate>${mode==='new'?field('roomName','House name','<input name="roomName" id="roomName" maxlength="40" placeholder="The Sunday House" required>'):own.length?own.map(r=>`<label class="choice ${r.members.length>=4?'disabled':''}"><input type="radio" name="roomId" value="${r.id}"${r.members.length>=4?' disabled':''}><span><strong>${esc(r.name)}</strong><small>${r.members.length} / 4 roomies${r.members.length>=4?' · Full':''}</small></span></label>`).join(''):`<div class="info-box">No saved rooms yet. Choose New room to create one.</div>`}${errorSlot()}<div class="community-actions"><button class="btn" type="submit"${mode==='existing'&&!own.some(r=>r.members.length<4)?' disabled':''}>${mode==='new'?'Create room & simulate invite':'Simulate invitation'} ↗</button></div><p class="help mt">No message is sent. You’ll simulate their response in the next step.</p></form>`,{to:'/person/'+id,label:'Profile'});}
  function invitationView(id){const inv=state.invitations.find(i=>i.id===id),p=inv&&person(inv.personId),r=inv&&room(inv.roomId);if(!p||!r)return notFound('This invitation is no longer available.','/load');return communityPage(['Invite','Preview'],inv.status==='joined'?'You’re in this together.':'A place for one more.',`Invite ${p.name.split(' ')[0]} to ${r.name}.`,`<div class="invitation-person">${avatar(p.name,p.color+' lg')}<div><h2>${esc(p.name)}</h2><span class="pill">${inv.status==='joined'?'Joined in demo':'Pending demo invitation'}</span></div></div><p class="help">${inv.status==='joined'?'Your sample roommate has joined this local room.':'Nobody has received a message. Try the next step by simulating their response.'}</p><p id="invitation-error" class="form-error" role="alert"></p><div class="community-actions">${inv.status==='pending'?`<button class="btn" data-action="simulate-join" data-id="${id}">Simulate ${esc(p.name.split(' ')[0])} joining</button>`:''}<button class="${inv.status==='pending'?'text-link':'btn'}" data-go="/room/${r.id}">Open our room ↗</button></div>${inv.status==='pending'?`<div class="community-footnote"><button class="text-link" data-action="cancel-invite" data-id="${id}">Cancel invitation</button></div>`:''}`,{to:'/person/'+p.id,label:'Profile'});}
  // Room UI composition stays here. The house engine receives only room identity and members.
  function roomView(id) {
    const r=room(id); if(!r)return notFound('You haven’t joined this room in this browser.','/homes');
    state.lastRoom=id;save();
    return `<section class="house-shell" data-room-id="${esc(id)}">
      <div class="house-stage-wrap"><div id="house-stage"><p>Getting your house ready…</p></div>
        <div class="house-scene-status"><span id="house-hover-hint"></span></div>
      </div>
      <div class="house-mood">${D.moodSelect(true)}</div>
      <header class="house-identity"><h1>${esc(r.name)}</h1></header>
      <div class="house-camera-actions house-quiet-controls" aria-label="House camera controls">
        <button data-h-action="frame" aria-label="Reset angle" title="Reset angle">${icon('resetAngle')}</button>
        <button data-h-action="help" aria-label="Help" title="Help">${icon('help')}</button>
      </div>
      <div class="house-settings house-quiet-controls"><button data-h-action="arrangement" aria-label="Arrangement" title="Arrangement">${icon('calendar')}</button><button data-h-action="edit" aria-label="Edit mode" title="Edit mode">${icon('gear')}</button></div>
      <div class="house-exit house-quiet-controls"><button data-go="/homes" aria-label="Leave room" title="Leave room">${icon('logout')}</button></div>
      <aside class="house-residents" aria-label="Roommates and Pip">
        <div class="house-member-stack">${[...r.members].sort((a,b)=>(b.id==='self')-(a.id==='self')).map(m=>`<button class="house-resident ${m.id==='self'?'is-self':'is-roommate'}" data-h-action="member" data-id="${esc(m.id)}" aria-label="${esc(memberName(m))}" title="${esc(memberName(m))}">${avatar(memberName(m),m.color||'sage')}</button>`).join('')}</div>
        <button class="house-resident house-cat-avatar" data-h-action="pet-status" aria-label="Pip’s status" title="Pip’s status" aria-expanded="false" aria-controls="house-pet-panel">${icon('cat')}<span class="house-pet-alert" hidden></span></button>
      </aside>
      <section id="house-pet-panel" class="house-pet-panel" aria-label="Pip’s status" hidden>
        <div class="house-pet-title"><strong>Pip</strong><button data-h-action="close-pet" aria-label="Close Pip’s status">×</button></div>
        <p data-pet-absent hidden>Pip is not in the room.</p>
        <div data-pet-vitals><div class="house-pet-row"><span>Hunger</span><strong data-pet-hunger>full</strong></div>
        <small data-pet-countdown hidden></small><div class="house-pet-row"><label for="house-pet-health">Health</label><span data-pet-health>100 / 100</span></div>
        <progress id="house-pet-health" max="100" value="100">100 / 100</progress></div><label class="house-pet-mute"><input type="checkbox" data-pip-mute>Mute meows</label><label class="house-meow-volume">Meow volume <output data-pip-volume-label>70%</output><input type="range" min="0" max="100" value="70" step="1" data-pip-volume aria-label="Meow volume"></label><button type="button" data-h-action="pip-preview">Test meow</button>
      </section>
      <div id="house-editor-ui"></div><p id="house-message" role="status" aria-live="polite"></p>
      <dialog id="house-dialog" aria-labelledby="house-dialog-title"></dialog>
    </section>`;
  }
  function profileView(){return `<div class="content-width">${back('/','Welcome')}${intro('MY PROFILE','A little about you.','Your display name and living habits are saved only in this browser.')}<div class="grid-two"><div class="panel"><form id="profile-form" novalidate><div class="profile-hero">${avatar(state.user.name,'lg')}<div><h2>${esc(state.user.name)}</h2><span class="pill">Demo profile</span></div></div>${field('name','Display name',`<input name="name" id="name" maxlength="32" value="${esc(state.user.name)}" required>`)}${field('campus','School or neighbourhood (optional)',`<input name="campus" id="campus" maxlength="60" value="${esc(state.user.campus)}" placeholder="e.g. Near campus">`)}${errorSlot()}<button class="btn" type="submit">Save profile</button></form></div><div class="stack"><div class="panel"><h2 class="inline-icon">${icon('leaf')}Living habits</h2><p class="mt-sm">${state.user.habits?'Your preferences are saved. Revisit them whenever you like.':'Add your routines to start better roommate conversations.'}</p><button class="btn secondary mt" data-go="/habits">${state.user.habits?'Edit habits':'Add habits'}</button></div><div class="panel"><h3>Taking a break?</h3><p class="small mt-sm">Logging out keeps your demo rooms and preferences in this browser.</p><button class="btn text mt-sm" data-action="logout">${icon('logout')}Log out of demo</button></div><section class="panel demo-reset-panel"><h3>A fresh demo</h3><p id="demo-reset-description" class="small mt-sm">Clear this browser’s demo profile, all rooms, tasks, uploads and preferences, then replay the welcome. Your default house stays the same.</p><button class="btn secondary mt" data-action="reset-demo" aria-describedby="demo-reset-description">${icon('resetAngle')}Reset demo</button></section></div></div></div>`;}
  function notFound(message,to='/'){return `<section class="panel empty-state">${D.house()}<h1>Let’s get you home.</h1><p>${esc(message)}</p><button class="btn" data-go="${to}">Go back</button></section>`;}
  function stopForDemoReset(){
    D.cleanup();
    if(houseRuntime){houseRuntime.destroy({persist:false});houseRuntime=null;}
    if(modal.open)modal.close();
  }
  function restartDemo(){
    stopForDemoReset();
    sessionStorage.removeItem('roombloom-intro-seen');
    history.replaceState(null,'','#/login');
    location.reload();
  }
  async function resetDemo(button){
    if(resettingDemo)return;
    resettingDemo=true;button.disabled=true;button.textContent='Resetting…';app.inert=true;
    stopForDemoReset();
    try{await RoomBloomHouse.DemoReset.clear();restartDemo();}
    catch(error){resettingDemo=false;app.inert=false;render();showToast('Demo reset could not finish. '+error.message);}
  }
  window.addEventListener('storage',event=>{
    if(event.storageArea===localStorage&&event.key===RoomBloomHouse.DemoReset.signalKey&&event.newValue){
      resettingDemo=true;restartDemo();
    }
  });
  function captureRoom(){
    if(!houseRuntime?.scene)return;const r=room(houseRuntime.options.roomId);if(!r)return;
    try{const scene=houseRuntime.scene;scene.render(houseRuntime.animal.view());const canvas=document.createElement('canvas');canvas.width=600;canvas.height=Math.round(600*scene.canvas.height/scene.canvas.width);canvas.getContext('2d').drawImage(scene.canvas,0,0,canvas.width,canvas.height);r.thumbnail=canvas.toDataURL('image/webp',.72);r.previewAt=Date.now();save();}catch(_){}
  }
  function render({cloudCovered=false}={}){
    if(resettingDemo)return;
    const {path,params}=route(),mode=hubMode(path),hub=app.querySelector('.welcome-page[data-hub-mode]');
    if(!cloudCovered){
      D.cancelRoomEntry();
      const destination=state.loggedIn&&path.startsWith('/room/')&&room(path.split('/')[2]);
      if(destination&&houseRuntime?.options.roomId!==destination.id){
        for(const dialog of document.querySelectorAll('dialog[open]'))dialog.close();
        D.enterRoom(()=>{if(!resettingDemo&&route().path===path)render({cloudCovered:true});});return;
      }
      if(houseRuntime&&!destination){
        for(const dialog of document.querySelectorAll('dialog[open]'))dialog.close();
        D.leaveRoom(()=>{if(!resettingDemo&&route().path===path)render({cloudCovered:true});});return;
      }
    }
    // These are expanded states of one screen. Keep the header, cards, focus and scroll in place.
    if(state.loggedIn&&mode&&hub){
      if(modal.open)modal.close();document.body.dataset.page=mode==='welcome'?'welcome':mode;
      D.setCursorEnabled(true);D.hubSwitch(hub,mode);return;
    }
    D.cleanup({keepRoomEntry:cloudCovered});if(houseRuntime){captureRoom();houseRuntime.destroy();houseRuntime=null;}
    document.body.classList.remove('has-house','house-editing');if(modal.open)modal.close();let body;
    document.body.dataset.page=!state.loggedIn?'login':path==='/login'||path==='/'?'welcome':path.split('/')[1];
    if(!state.loggedIn){if(path!=='/'&&path!=='/login')returnAfterLogin=path+(params.toString()?'?'+params.toString():'');body=loginView();}
    else{const parts=path.split('/').filter(Boolean);if(path==='/'||path==='/login')body=welcomeView();else if(path==='/homes')body=homesView();else if(path==='/create')body=createView();else if(path==='/join')body=joinView(params);else if(parts[0]==='preview')body=previewView(parts[1]);else if(path==='/load')body=loadView(params);else if(path==='/find')body=findView();else if(path==='/habits')body=habitsView();else if(path==='/plaza')body=plazaView(params);else if(parts[0]==='person')body=personView(parts[1]);else if(parts[0]==='invite')body=inviteView(parts[1],params);else if(parts[0]==='invitation')body=invitationView(parts[1]);else if(parts[0]==='room')body=roomView(parts[1]);else if(path==='/profile')body=profileView();else body=notFound('This page does not exist in the demo.');}
    app.innerHTML=shell(body);const houseRoot=app.querySelector('.house-shell');
    if(houseRoot){document.body.classList.add('has-house');const currentRoom=room(houseRoot.dataset.roomId);houseRuntime=RoomBloomHouse.mount(houseRoot,{roomId:currentRoom.id,memberId:'self',members:currentRoom.members.map(m=>{const p=m.id==='self'?state.user:people.find(p=>p.id===m.id)||m;return {...p,id:m.id,name:memberName(m),habits:p.habits||Object.fromEntries(['sleep','clean','noise','guests','pets'].filter(k=>p[k]).map(k=>[k,p[k]]))};})});}
    D.setCursorEnabled(state.loggedIn&&!houseRoot);
    document.title=(app.querySelector('h1,h2')?.textContent||'Welcome')+' · Bloom Room';window.scrollTo(0,0);document.getElementById('main').focus({preventScroll:true});
    if(!state.loggedIn)D.login();else D.pageIn(document.getElementById('main'));
  }
  function dialog(title,body){lastFocus=document.activeElement;document.getElementById('modal-content').innerHTML=`<div class="dialog-title"><h2 id="modal-title">${esc(title)}</h2><button class="close" data-action="close-modal" aria-label="Close dialog">${icon('close')}</button></div>${body}`;modal.showModal();}
  modal.addEventListener('close',()=>{if(lastFocus?.isConnected)lastFocus.focus();});
  modal.addEventListener('click',e=>{if(e.target===modal){const b=modal.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)modal.close();}});
  async function copy(value){try{if(!navigator.clipboard)throw new Error('No clipboard');await navigator.clipboard.writeText(value);showToast('Copied. Demo invites work only with data in this browser.');}catch(_){dialog('Copy your demo invite',`<p>Select and copy the text below. It only opens rooms available in this browser.</p><textarea class="copy-fallback" readonly aria-label="Invite to copy">${esc(value)}</textarea><div class="dialog-actions"><button class="btn" data-action="close-modal">Done</button></div>`);modal.querySelector('textarea').select();}}
  function validateName(name){if(name.trim().length<2)return 'Give your room a name with at least 2 characters.';if(name.trim().length>40)return 'Keep the room name to 40 characters or fewer.';if(directory().some(r=>r.name.toLowerCase()===name.trim().toLowerCase()))return 'That room name is already used in this demo. Choose a different name, or join the existing room.';return '';}
  function makeRoom(name){const id='room-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,6);let code;do{code='RB'+Math.random().toString(36).slice(2,7).toUpperCase();}while(directory().some(r=>r.code===code));const r={id,name:name.trim(),code,members:[{id:'self',color:'sage'}],createdAt:Date.now(),sample:false};state.rooms.push(r);return r;}
  function lookupInvite(value){let token=value.trim();if(token.length>2048)return null;if(token.includes('://')){try{const u=new URL(token);const hashQ=u.hash.split('?')[1];const hash=new URLSearchParams(hashQ||'');token=hash.get('code')||u.searchParams.get('code')||u.pathname.split('/').filter(Boolean).pop()||token;}catch(_){return null;}}return directory().find(r=>r.code.toLowerCase()===token.toLowerCase()||r.name.toLowerCase()===token.toLowerCase());}
  document.addEventListener('input',e=>{if(e.target.matches('input,select,textarea'))e.target.removeAttribute('aria-invalid');});
  document.addEventListener('submit',e=>{const f=e.target;if(!(f instanceof HTMLFormElement))return;e.preventDefault();const v=Object.fromEntries(new FormData(f));
    if(f.id==='login-form'||f.id==='profile-form'){const name=String(v.name||'').trim();if(name.length<1||name.length>32)return formError(f,f.id==='login-form'?'Enter an ID between 1 and 32 characters.':'Enter a display name between 1 and 32 characters.','name');state.user.name=name;if(f.id==='profile-form'){state.user.campus=String(v.campus||'').trim();save();render();showToast('Profile saved.');}else{state.loggedIn=true;save();const next=returnAfterLogin||'/';returnAfterLogin='';go(next);}return;}
    if(f.id==='create-form'){const name=String(v.roomName||'').trim(),err=validateName(name);if(err)return formError(f,err,'roomName');const r=makeRoom(name);save();go('/room/'+r.id);showToast('Your room is ready. Sprout has moved in.');return;}
    if(f.id==='join-form'){const value=String(v.invite||'').trim();if(!value)return formError(f,'Enter an invite code, link, or room name.','invite');if(value.toUpperCase()==='EXPIRED')return formError(f,'This sample invitation has expired. Ask for a new invite, or try RB42.','invite');const r=lookupInvite(value);if(!r)return formError(f,'We couldn’t find that room. Check the invite, or try the sample code RB42.','invite');go('/preview/'+r.id);return;}
    if(f.id==='habits-form'){state.user.habits=v;save();go('/find');showToast('Your living habits are saved.');return;}
    if(f.id==='filters-form'){go('/plaza?'+new URLSearchParams(v).toString());return;}
    if(f.id==='invite-form'){const id=f.dataset.person;if(state.connections[id]!=='accepted')return formError(f,'A mutual demo connection is needed before inviting.');let r;if(f.dataset.mode==='new'){const err=validateName(String(v.roomName||''));if(err)return formError(f,err,'roomName');r=makeRoom(v.roomName);}else{r=room(v.roomId);if(!r)return formError(f,'Choose a room, or create a new one.');}if(r.members.length>=4)return formError(f,'This room is full. Choose or create another room.');if(r.members.some(m=>m.id===id))return go('/room/'+r.id);const inv={id:'invite-'+Date.now().toString(36),personId:id,roomId:r.id,status:'pending'};state.invitations.push(inv);save();go('/invitation/'+inv.id);return;}
  });
  document.addEventListener('click',e=>{const b=e.target.closest('button[data-go],button[data-action]');if(!b||b.disabled)return;if(b.dataset.go){go(b.dataset.go);return;}const id=b.dataset.id;
    switch(b.dataset.action){
      case 'house-preview':{
        const archived=b.dataset.archive==='true',r=archived?state.archives.find(r=>r.id===id):room(id);if(!r)return;
        dialog(r.name,`<div class="house-memory">${r.thumbnail?`<img src="${esc(r.thumbnail)}" alt="Saved preview of ${esc(r.name)}">`:`<div class="memory-placeholder">${D.house()}<p>A preview will be saved after your first visit.</p></div>`}</div><p class="memory-caption">${archived?'A little home from your story. Left '+esc(new Date(r.archivedAt).toLocaleDateString()):'Your shared space is waiting.'}</p><div class="dialog-actions">${archived?`<button class="btn" data-action="restore-room" data-id="${esc(id)}">Return to this home</button>`:`<button class="btn" data-go="/room/${esc(id)}">Open room</button>`}</div>`);break;
      }
      case 'archive-room':{
        const r=room(id);if(!r)return;dialog('Keep a little memory?',`<p>Leave ${esc(r.name)} and keep its last room preview in your Archive. Your room layout will remain saved in this browser.</p><div class="dialog-actions"><button class="btn secondary" data-action="close-modal">Stay here</button><button class="btn" data-action="confirm-archive" data-id="${esc(id)}">Leave & archive</button></div>`);break;
      }
      case 'confirm-archive':{
        const r=room(id);if(!r)return;captureRoom();state.archives=state.archives.filter(a=>a.id!==id);state.archives.push({...JSON.parse(JSON.stringify(r)),archivedAt:Date.now()});r.members=r.members.filter(m=>m.id!=='self');state.invitations=state.invitations.filter(i=>i.roomId!==id||i.status!=='pending');if(state.lastRoom===id)state.lastRoom=null;save();go('/load?tab=archive');showToast('A little memory, safely kept.');break;
      }
      case 'restore-room':{
        const archived=state.archives.find(r=>r.id===id),live=state.rooms.find(r=>r.id===id);if(!archived||!live)return;
        if(live.members.length>=4){showToast('This home has no open seats right now.');break;}if(!live.members.some(m=>m.id==='self'))live.members.push({id:'self',color:'sage'});state.archives=state.archives.filter(r=>r.id!==id);save();go('/room/'+id);break;
      }
      case 'about':dialog('A little demo, a lot of possibility.',`<p>Bloom Room is an experimental roommate app.</p><ul><li>Login currently uses a local ID, not a connected account.</li><li>Profiles, matches, and invitations are simulated.</li><li>Rooms and preferences are saved in this browser only.</li><li>No messages, payments, or notifications are sent.</li></ul><p class="small">The 3D house editor is available in Our Room. Tasks, household schedules and message boards are available through the objects in your house. Moving or renaming these files may change which local save your browser can access.</p><div class="dialog-actions"><button class="btn" data-action="close-modal">Got it</button></div>`);break;
      case 'close-modal':modal.close();break;
      case 'fill-invite':{const input=document.getElementById('invite');input.value=b.dataset.value;input.focus();break;}
      case 'confirm-join':{let r=directory().find(x=>x.id===id);if(!r)return go('/join');if(room(id))return go('/room/'+id);if(r.members.length>=4){document.getElementById('join-error').textContent='This room is full. Try another invitation.';return;}r=JSON.parse(JSON.stringify(r));r.members.push({id:'self',color:'sage'});state.rooms=state.rooms.filter(x=>x.id!==r.id);state.rooms.push(r);state.archives=state.archives.filter(x=>x.id!==r.id);save();go('/room/'+id);showToast('You’ve joined '+r.name+'.');break;}
      case 'request':if(person(id)){state.connections[id]='pending';save();render();showToast('Demo connection requested. Simulate a response to continue.');}break;
      case 'respond':if(person(id)&&state.connections[id]==='pending'&&['accepted','declined'].includes(b.dataset.value)){state.connections[id]=b.dataset.value;save();render();showToast(b.dataset.value==='accepted'?'Demo connection accepted.':'Demo connection declined.');}break;
      case 'cancel-request':delete state.connections[id];save();render();showToast('Demo request cancelled.');break;
      case 'simulate-join':{const i=state.invitations.find(x=>x.id===id);const r=i&&room(i.roomId),p=i&&person(i.personId);if(!r||!p)return;if(i.status==='joined')return go('/room/'+r.id);if(!r.members.some(m=>m.id===p.id)){if(r.members.length>=4){document.getElementById('invitation-error').textContent='This room is now full. Cancel this invitation and choose another room.';return;}r.members.push({id:p.id,name:p.name,color:p.color,demo:true});}i.status='joined';save();go('/room/'+r.id);showToast(p.name.split(' ')[0]+' joined your room in the demo.');break;}
      case 'cancel-invite':{const i=state.invitations.find(x=>x.id===id);if(!i)return;state.invitations=state.invitations.filter(x=>x.id!==id);save();go('/person/'+i.personId);showToast('Demo invitation cancelled.');break;}
      case 'copy':copy(b.dataset.value);break;
      case 'clear-filters':go('/plaza');break;
      case 'room-invite':{const r=room(id);if(!r)return;const link=location.href.split('#')[0]+'#/join?code='+encodeURIComponent(r.code);dialog('Invite to '+r.name,`<p>${r.members.length>=4?'All 4 seats are filled.':'Use this code to explore joining this room.'}</p><div class="invite-code">${esc(r.code)}</div><div class="row">${copyButton(r.code)}${copyButton(link,'Copy demo link')}</div><p class="help mt">This is a local demo. The link does not share room data with another browser or device.</p><div class="dialog-actions"><button class="btn secondary" data-go="/plaza">Find a demo roommate</button></div>`);break;}
      case 'meet-sprout':dialog('Meet Sprout.',`<div style="width:100px;margin:20px auto">${plant()}</div><p>Your shared plant is part of this little home. Personal task reminders and growth rewards are planned for the next version.</p><div class="dialog-actions"><button class="btn" data-action="close-modal">Nice to meet you</button></div>`);break;
      case 'coming-decor':dialog('Make it yours, soon.',`<p>Room decorating is planned for the next version. It will include moving furniture, adding decorations, and clear Save / Cancel controls.</p><div class="dialog-actions"><button class="btn" data-action="close-modal">Back to my room</button></div>`);break;
      case 'reset-demo':resetDemo(b);break;
      case 'logout':state.loggedIn=false;returnAfterLogin='';save();go('/login');break;
    }
  });
  document.querySelector('.skip-link').addEventListener('click',e=>{e.preventDefault();document.getElementById('main').focus();});
  window.addEventListener('hashchange',render);
  // Only restore on a fresh default entry; explicit links and the Leave room action keep their destination.
  if(state.loggedIn&&(!location.hash||location.hash==='#/'||location.hash==='#/login')&&room(state.lastRoom))history.replaceState(null,'','#/room/'+state.lastRoom);
  render();
})();
